/**
 * 成功案例（24 个）—— 每个可展开为五段档案：起点 / 诊断 / 调整 / 受挫 / 结果
 * 前 6 条对应客户提供的真实去向；其余为示例，上线前替换。
 *
 * group 用于第二维筛选：life / eng / comp / phys / env / social（与导师、课题一致）
 */
module.exports = [
  {
    inst: 'princeton', level: 'ug', year: 2026, group: 'life', real: true,
    fromZh: '国内公立国际部 · 高一启动', fromEn: 'Public school int’l division · started Grade 10',
    progZh: '本科 · 理科方向', progEn: 'Undergraduate · Sciences',
    quoteZh: '两年只追一个问题。从高一读文献起步，到高三交出一份能逐行为之辩护的分析——申请材料由家庭自己完成，我们只负责让他有东西可写。',
    quoteEn: 'Two years on a single question. From literature reading in Grade 10 to an analysis he could defend line by line in Grade 12. The family wrote the application themselves; our job was to make sure he had something to write about.',
    stats: [[24, '个月长线培养', 'months, institute track'], [1, '位导师全程', 'mentor throughout'], [1, '份独立分析', 'independent analysis']],
    phases: {
      startZh: '高一，成绩很好，活动很多，但没有一件事做超过三个月。第一次谈话里他说对免疫系统"为什么会攻击自己"这件事想了很久。',
      startEn: 'Grade 10, excellent grades, many activities, none lasting more than three months. In our first conversation he said he had long wondered why the immune system attacks itself.',
      diagZh: '不缺能力，缺连续性。我们建议砍掉七项活动里的五项，只留一条线。',
      diagEn: 'No shortage of ability — a shortage of continuity. We recommended dropping five of seven activities and keeping one thread.',
      changeZh: '进入长线培养轨道，第一年读文献与跟组会，第二年领一个关于抗体衰减的子问题，做数据清洗与可视化。',
      changeEn: 'Onto the institute track: year one reading and group meetings, year two an owned sub-question on antibody waning, doing the cleaning and visualisation.',
      wrongZh: '第二年春天，他做的第一版分析被导师指出混淆了两个队列，三个月的图作废。他重做了。',
      wrongEn: 'In the spring of year two his first analysis was found to have conflated two cohorts; three months of figures were discarded. He redid them.',
      outcomeZh: '高三秋季，一份他能逐行解释的独立分析，加一封写了"混淆队列"那件事的推荐信。录取普林斯顿。',
      outcomeEn: 'By the autumn of Grade 12: an independent analysis he could explain line by line, and a letter that told the cohort story. Admitted to Princeton.',
    },
  },
  {
    inst: 'princeton', level: 'ug', year: 2026, group: 'comp', real: true,
    fromZh: '美高 · 高二启动', fromEn: 'US high school · started Grade 11',
    progZh: '本科 · 工程方向', progEn: 'Undergraduate · Engineering',
    quoteZh: '他会写代码，但从没为别人写过代码。一段可远程的政策数据课题，让他第一次经历了"别人要跑我的程序"是什么感觉。',
    quoteEn: 'He could code, but had never written code for someone else to use. A remote policy-data placement gave him his first experience of another person needing to run his program.',
    stats: [[11, '个月', 'months'], [1, '个并入代码库', 'merged codebase'], [3, '轮 README 重写', 'README rewrites']],
    phases: {
      startZh: '美高高二，编程竞赛奖项一堆，GitHub 上全是自己玩的小项目，没有一个有第二个使用者。',
      startEn: 'Grade 11 at a US high school, a pile of programming awards, a GitHub full of toy projects — none with a second user.',
      diagZh: '技术没问题，问题是没有"交付"过。招生官分不清一个会写代码的人和一个能在团队里工作的人。',
      diagEn: 'Technically fine; the gap was that he had never delivered. A committee cannot tell a coder from someone who can work in a team.',
      changeZh: '匹配到一个通勤数据的居住隔离指标课题，任务很明确：把研究员的原型代码重写成可复现的模块。',
      changeEn: 'Matched to a segregation-index project on commuting data, with one clear task: rewrite the researcher’s prototype into a reproducible module.',
      wrongZh: 'README 被退回三次。第一次导师的评语只有一句："我按你写的步骤跑不起来。"',
      wrongEn: 'The README came back three times. The first time the mentor’s only comment was: “I followed your steps and it does not run.”',
      outcomeZh: '模块并入课题组代码库，提交记录里有他的名字。申请季他写的是这件事，不是奖项。录取普林斯顿。',
      outcomeEn: 'The module was merged with his name in the commit log. His application was about that, not the awards. Admitted to Princeton.',
    },
  },
  {
    inst: 'harvard', level: 'ms', year: 2026, group: 'life', real: true,
    fromZh: '华五本科 · 生物科学 · 大三启动', fromEn: 'Mainland C9 university · Biology · started junior year',
    progZh: '医学院 · 硕士', progEn: 'Harvard Medical School · Master’s',
    quoteZh: '二十二个月，两个实验室，两篇共同署名论文，以及一份敢于和领域内主流观点争辩、而非复述文献的研究计划书。',
    quoteEn: 'Twenty-two months across two laboratories, two co-authored papers, and a research statement that argued with the field rather than summarising it.',
    stats: [[22, '个月', 'months'], [2, '篇论文', 'papers'], [4, '个 offer', 'offers']],
    phases: {
      startZh: '大三，成绩优异，一个暑期科研，个人陈述在描述整个领域而不是她在其中的位置。三位推荐人里两位只在大课上教过她。',
      startEn: 'Junior year, excellent transcript, one summer of research, a statement describing the field rather than her place in it. Two of three recommenders had taught her only in lectures.',
      diagZh: '不是成就不够，是没有归属。档案里没有一样东西是她能为之辩护的。',
      diagEn: 'Not a shortage of achievement — a shortage of ownership. Nothing in the file was hers to defend.',
      changeZh: '进入一个免疫学实验室做细胞因子信号的子问题，砍掉两段不相关实习。路线图：技术与数据 11 个月，写作 5 个月。',
      changeEn: 'Into an immunology laboratory on a cytokine-signalling sub-question; two unrelated internships dropped. Roadmap: eleven months of technique and data, five of writing.',
      wrongZh: '第七个月主实验无法复现，四个月的数据作废。她重建了方案，这段经历后来成了研究计划书里最有力的一段。',
      wrongEn: 'In month seven the primary assay failed to replicate; four months of data were lost. She rebuilt the protocol, and that recovery became the strongest paragraph in her statement.',
      outcomeZh: '一篇期刊论文第二作者，一篇共同作者。面试里五个问题三个问她的数据。录取哈佛医学院硕士项目。',
      outcomeEn: 'Second author on one journal paper, co-author on another. Three of five interview questions were about her data. Admitted to a master’s programme at Harvard Medical School.',
    },
  },
  {
    inst: 'berkeley', level: 'ug', year: 2026, group: 'eng', real: true,
    fromZh: '深圳 · IB 课程 · 高一启动', fromEn: 'Shenzhen · IB curriculum · started Grade 10',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '一个喜欢拆东西的女孩。我们没有让她去做"科研"，而是让她在一个器件实验室里把一台传感器的原型做到第七版。',
    quoteEn: 'A girl who liked taking things apart. We did not send her to “do research”; we put her in a device laboratory and had her carry a sensor prototype to its seventh version.',
    stats: [[2, '个暑期', 'summers'], [7, '版原型', 'prototype versions'], [1, '份编号存档', 'numbered archive']],
    phases: {
      startZh: '高一，IB 预估分很高，课外几乎没有理工类经历——她自己说"没人告诉我可以做什么"。',
      startEn: 'Grade 10, strong predicted IB, almost no STEM experience outside class — “nobody told me what I could do”, she said.',
      diagZh: '动手能力明显，但没有出口。适合工程实现而不是理论。',
      diagEn: 'Obvious practical ability with no outlet. Suited to engineering build rather than theory.',
      changeZh: '两个暑期在地进入一个生物医学工程实验室，任务是把一款可穿戴传感器的运动伪影校正模块从原型做到可测试。',
      changeEn: 'Two on-site summers in a biomedical engineering laboratory, carrying a wearable sensor’s motion-artefact correction from prototype to testable.',
      wrongZh: '第三版把电路烧了。导师没有批评，只是把烧掉的板子编号存档，作为第三版。',
      wrongEn: 'Version three burned out the circuit. The mentor did not criticise; he numbered the dead board and archived it as version three.',
      outcomeZh: '第七版通过测试。面试官问得最多的是"你怎么从第三版走到第七版"。录取伯克利。',
      outcomeEn: 'Version seven passed testing. The interviewer’s most repeated question was how she got from three to seven. Admitted to Berkeley.',
    },
  },
  {
    inst: 'washington', level: 'ug', year: 2026, group: 'comp', real: true,
    fromZh: '杭州 · 公立国际部 · 高二启动', fromEn: 'Hangzhou · public school int’l division · started Grade 11',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '起步晚，时间紧。一个范围收得很小的教育数据课题，胜过我们建议她放弃的那四项零散活动。',
    quoteEn: 'A late start and a tight window. One tightly scoped education-data project beat the four scattered activities we advised her to drop.',
    stats: [[8, '个月', 'months'], [4, '项活动砍掉', 'activities dropped'], [1, '份可复现分析', 'reproducible analysis']],
    phases: {
      startZh: '高二下，距离申请只有一年多。活动栏里有志愿、模联、校刊、两个夏校，彼此无关。',
      startEn: 'Spring of Grade 11, little more than a year to applications. Volunteering, MUN, a school magazine, two summer schools — none related to the others.',
      diagZh: '时间不够做两件事，只能做一件。她对"为什么有的同学越补课成绩越差"这个问题有真实的好奇。',
      diagEn: 'Not enough time for two things; only one. She had a genuine curiosity about why some classmates got worse the more tutoring they had.',
      changeZh: '一个可远程的在线学习平台数据课题，每周六到八小时，问题被收窄到"练习时长与正确率的关系在什么条件下反转"。',
      changeEn: 'A remote online-learning-data project, six to eight hours a week, narrowed to “under what conditions does the relationship between practice time and accuracy reverse”.',
      wrongZh: '第四个月她想把问题扩大，导师拒绝了："先把小的做对。"她当时很不服气。',
      wrongEn: 'In month four she wanted to widen the question. The mentor refused: “Get the small one right first.” She was not pleased.',
      outcomeZh: '一份别人能跑的分析，一封写了"她想扩大问题、后来自己承认扩大是错的"的推荐信。录取华盛顿大学。',
      outcomeEn: 'An analysis a stranger could run, and a letter that recorded her wanting to widen the question and later conceding it was a mistake. Admitted to the University of Washington.',
    },
  },
  {
    inst: 'buffalo', level: 'phd', year: 2026, group: 'comp', real: true,
    fromZh: '内地非重点本科 · 计算机 · 大四启动', fromEn: 'Mainland non-elite university · CS · started senior year',
    progZh: '博士 · 全额奖学金', progEn: 'Doctoral · Fully funded',
    quoteZh: '上一轮六投零面试。我们改按"问题"而非"排名"检索导师，他的代码恰好碰上一位教授待解的问题。',
    quoteEn: 'Six applications, zero interviews the previous cycle. We re-ran the search by problem rather than ranking, and his code happened to meet a professor’s open question.',
    stats: [[2, '个申请季', 'cycles'], [3, '位导师去信', 'advisors contacted'], [1, '个全奖', 'funded offer']],
    phases: {
      startZh: '非重点本科最后一年，没有论文，实验室的名字美国委员会不认得，上一季六份申请全拒。',
      startEn: 'Final year at a non-elite university, no publication, a laboratory no US committee would recognise, six rejections the previous cycle.',
      diagZh: '不是弱，是不可见。档案里全是机构属性，没有个人属性；而且他按学校投的，那些系里没人做他的东西。',
      diagEn: 'Not weak — invisible. Everything in the file was institutional, nothing personal; and he had applied school-first, to departments where nobody worked on his problem.',
      changeZh: '九个月一个可远程计算课题，问题与他自己写过的代码重叠。他把代码重建到陌生人能跑的标准，课题组合并了。',
      changeEn: 'Nine months on a remote computational placement overlapping with code he had already written. He rebuilt it to a standard a stranger could run; the group merged it.',
      wrongZh: '他坚持再投同样的三个系。我们说分析显示那里没有人做他的问题。他还是投了，三个全拒。',
      wrongEn: 'He insisted on reapplying to three of the same departments. We said the analysis showed nobody there worked on his question. He applied anyway; all three rejected him.',
      outcomeZh: '与此同时，一个我们按问题检索出来的系给了全额资助的博士席位。家庭做了我们不建议的决定，那是他们的权利。',
      outcomeEn: 'Meanwhile a department we had found by searching for the problem offered a fully funded doctoral place. The family made a decision we advised against — their right.',
    },
  },

  /* ================= 示例：本科 ================= */
  {
    inst: 'cornell', level: 'ug', year: 2026, group: 'life',
    fromZh: '北京 · 公立国际部 · 高二启动', fromEn: 'Beijing · int’l division · started Grade 11',
    progZh: '生物工程 · 本科 · ED', progEn: 'Biological Engineering · BS · Early Decision',
    quoteZh: '标化很漂亮，却讲不出一个故事。九个月的免疫学实验室经历，给了她一个诚实的问题去追。',
    quoteEn: 'Strong scores, no story. Nine months in an immunology laboratory gave her one honest question to chase.',
    stats: [[9, '个月科研', 'months in lab'], [1, '篇会议海报', 'conference poster'], [6, '项活动砍掉', 'activities dropped']],
    phases: {
      startZh: '十一项活动，彼此无关。第一次谈话她讲了二十分钟外婆的自身免疫病为什么从没人向家里解释清楚。',
      startEn: 'Eleven activities, none connected. In the first conversation she spent twenty minutes on why her grandmother’s autoimmune diagnosis had never been explained to the family.',
      diagZh: '档案读起来"努力但可替代"。那二十分钟才是线索，而申请材料里只字未提。',
      diagEn: 'A file that read as diligent and interchangeable. Those twenty minutes were the thread; the application did not mention them.',
      changeZh: '砍掉六项活动，进入免疫学实验室的远程数据方向：文献筛选、图像定量、独立分析，每周八小时。',
      changeEn: 'Six activities dropped; into the remote data track of an immunology laboratory: screening, image quantification, then her own analysis, eight hours a week.',
      wrongZh: '她想要期刊发表。导师说不够格，拒绝支持投稿。我们站在导师一边。',
      wrongEn: 'She wanted a journal publication. The mentor said the work did not merit one and would not support submission. We backed the mentor.',
      outcomeZh: '工作以海报投往区域会议，她本人到场答辩。ED 录取康奈尔，面试官整场都在谈那张海报。',
      outcomeEn: 'The work went to a regional conference as a poster she defended in person. Admitted Early Decision; the interviewer spent the whole conversation on the poster.',
    },
  },
  {
    inst: 'hku', level: 'ug', year: 2026, group: 'life',
    fromZh: '深圳 · IB 课程 · 高一启动', fromEn: 'Shenzhen · IB curriculum · started Grade 10',
    progZh: '内外全科医学 · 本科', progEn: 'Medicine · MBBS',
    quoteZh: '两年在国际公益组织做临床邻近的公共卫生工作，以及一份由她亲手参与采集与清洗的区级筛查数据集。',
    quoteEn: 'Two years of clinical-adjacent public health work with an international NGO, and a district screening dataset she helped collect and clean herself.',
    stats: [[24, '个月', 'months'], [1, '份公开报告', 'published report'], [42, 'IB', 'IB points']],
    phases: {
      startZh: '想学医，简历上只有一次医院志愿——两天，发传单。',
      startEn: 'Wanted medicine; the only relevant entry was two days of hospital volunteering, handing out leaflets.',
      diagZh: '医学院看的不是"想学医"，是"见过真实的病人和真实的数据"。她两样都没有。',
      diagEn: 'Medical schools do not look for wanting medicine; they look for having seen real patients and real data. She had neither.',
      changeZh: '进入一个国际卫生公益组织的项目评估团队，参与社区筛查的田野采集，然后负责数据清洗。',
      changeEn: 'Onto an international health NGO’s programme-evaluation team: field collection for a community screening, then responsibility for cleaning the data.',
      wrongZh: '第一批采集的数据有三成因为表格填错作废。她自己设计了新的采集表。',
      wrongEn: 'Thirty percent of the first batch was lost to form errors. She designed a new collection form herself.',
      outcomeZh: '她的名字进入机构的公开报告。港大医学院录取。',
      outcomeEn: 'Her name appears in the organisation’s published report. Admitted to HKU Medicine.',
    },
  },
  {
    inst: 'ntu', level: 'ug', year: 2026, group: 'phys',
    fromZh: '苏州 · 国际学校 · 高一启动', fromEn: 'Suzhou · international school · started Grade 10',
    progZh: '材料科学 · 本科', progEn: 'Materials Science · BEng',
    quoteZh: '三年只追一个材料学问题：高一读文献，高三共同署名一篇会议论文。推荐信几乎是自己写出来的。',
    quoteEn: 'Three years on one materials question, from reading in Grade 10 to co-authorship on a conference paper in Grade 12. The letter almost wrote itself.',
    stats: [[3, '年长线培养', 'years, institute track'], [1, '篇会议论文', 'conference paper'], [1, '位导师全程', 'mentor throughout']],
    phases: {
      startZh: '高一，对"手机电池为什么会鼓包"好奇了很久，除此之外一片空白。',
      startEn: 'Grade 10, a long-standing curiosity about why phone batteries swell, and otherwise a blank.',
      diagZh: '起步早，方向明确，适合长线。',
      diagEn: 'Early start, clear direction — a candidate for the long track.',
      changeZh: '进入一位材料教授的长线轨道。第一年读文献，第二年负责电极材料循环测试的一个子问题，第三年参与成稿。',
      changeEn: 'Onto a materials professor’s long track: year one reading, year two a sub-question on electrode cycling tests, year three contributing to the manuscript.',
      wrongZh: '第二年卡了四个月，测试数据的重复性一直不达标。导师没有换题，让她把问题找出来——是手套箱的湿度。',
      wrongEn: 'Stuck for four months in year two: cycling data would not repeat. The mentor did not change the topic; he made her find the cause — glovebox humidity.',
      outcomeZh: '共同作者出现在会议论文上。推荐信里写了那四个月。录取南洋理工。',
      outcomeEn: 'Co-author on the conference paper; the letter described the four months. Admitted to NTU.',
    },
  },
  {
    inst: 'florida', level: 'ug', year: 2026, group: 'env',
    fromZh: '南京 · A-Level · 高二启动', fromEn: 'Nanjing · A-Level · started Grade 11',
    progZh: '环境工程 · 本科 · 奖学金', progEn: 'Environmental Engineering · BS · Merit award',
    quoteZh: '启动晚，窗口紧。一个范围收得很小的水质研究项目，胜过我们建议他放弃的那四项零散活动。',
    quoteEn: 'Late start, tight window. One well-scoped water-quality project beat the four scattered activities we advised him to drop.',
    stats: [[7, '个月', 'months'], [4, '项活动砍掉', 'activities dropped'], [1, '份奖学金', 'scholarship']],
    phases: {
      startZh: '高二，A-Level 预估 A*AA，活动是四个互不相关的夏校。',
      startEn: 'Grade 11, predicted A*AA, four unrelated summer schools.',
      diagZh: '七个月只能做一件事。他对家乡河道的水质有真实的关心。',
      diagEn: 'Seven months allows one thing. He cared genuinely about the river at home.',
      changeZh: '一个灌溉水微塑料沉降的课题，暑期在地做实验，学期内远程整理数据。',
      changeEn: 'A microplastics-settling project: on-site experiments over the summer, remote data curation during term.',
      wrongZh: '第一批样品因为保存不当全部作废。',
      wrongEn: 'The first batch of samples was lost to improper storage.',
      outcomeZh: '一份实验数据集和论文的方法部分。录取佛罗里达大学，附优秀奖学金。',
      outcomeEn: 'An experimental dataset and the methods section of a paper. Admitted to the University of Florida with a merit award.',
    },
  },
  {
    inst: 'upenn', level: 'ug', year: 2026, group: 'social',
    fromZh: '上海 · 美高 · 高一启动', fromEn: 'Shanghai · US-curriculum school · started Grade 10',
    progZh: '本科 · ED', progEn: 'Undergraduate · Early Decision',
    quoteZh: '一个文科生，被所有人劝去做"科研"。我们让她去做她真正会做的事：在一个政治学课题里做十四周的文本分析。',
    quoteEn: 'A humanities student everyone urged to “do research”. We had her do what she was actually good at: fourteen weeks of text analysis inside a political science project.',
    stats: [[14, '周', 'weeks'], [1, '份政策评论', 'policy commentary'], [12, '轮反驳', 'rounds of rebuttal']],
    phases: {
      startZh: '文科拔尖，被家长要求去做生物实验，做了两个月，讨厌。',
      startEn: 'Top of her class in the humanities, pushed by her parents into a biology laboratory for two months. She hated it.',
      diagZh: '方向错了，不是能力错了。',
      diagEn: 'The direction was wrong, not the ability.',
      changeZh: '换到一个联合国决议文本的议题演变课题，每周写一篇政策评论，由另一名学生逐句反驳。',
      changeEn: 'Switched to a project on topic evolution in UN resolution texts, writing a weekly policy commentary rebutted line by line by another student.',
      wrongZh: '前四周的评论被批"全是形容词"。',
      wrongEn: 'The first four weeks’ commentaries were dismissed as “all adjectives”.',
      outcomeZh: '第十二周的评论被导师转给了一位同事。ED 录取宾大。',
      outcomeEn: 'The twelfth week’s commentary was forwarded by the mentor to a colleague. Admitted Early Decision to Penn.',
    },
  },
  {
    inst: 'michigan', level: 'ug', year: 2026, group: 'eng',
    fromZh: '成都 · 公立高中 · 高二启动', fromEn: 'Chengdu · public high school · started Grade 11',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '公立体系的学生，没有"活动"这个概念。一个电动车电池老化的数据课题，让他第一次拥有了一件属于自己的作品。',
    quoteEn: 'A student from the public system, with no concept of “activities”. An EV battery-ageing data project gave him his first piece of work that was his own.',
    stats: [[10, '个月', 'months'], [1, '份可复现代码', 'reproducible code'], [0, '项其他活动', 'other activities']],
    phases: {
      startZh: '公立高中，理科竞赛省奖，课外活动栏几乎空白。',
      startEn: 'Public high school, provincial science-olympiad award, an almost empty activities list.',
      diagZh: '空白反而干净。一件做透的事比十件做浅的事强。',
      diagEn: 'A blank is at least clean. One thing done deeply beats ten done shallowly.',
      changeZh: '可远程的电池老化与驾驶数据关联课题，每周六小时。',
      changeEn: 'A remote project linking battery ageing to driving data, six hours a week.',
      wrongZh: '英文组会前两个月一句话没说过。导师让他每周提前写好一个问题发到群里。',
      wrongEn: 'Silent in English-language group meetings for two months. The mentor had him post one written question to the channel before each meeting.',
      outcomeZh: '一份带 README 的分析代码。录取密歇根。',
      outcomeEn: 'Analysis code with a README. Admitted to Michigan.',
    },
  },
  {
    inst: 'toronto', level: 'ug', year: 2025, group: 'social',
    fromZh: '广州 · 国际学校 · 高一启动', fromEn: 'Guangzhou · international school · started Grade 10',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '她想学经济，但只会背理论。一个最低工资面板数据的课题让她明白：经济学是用数据吵架。',
    quoteEn: 'She wanted economics but could only recite theory. A minimum-wage panel-data project taught her that economics is arguing with data.',
    stats: [[14, '周', 'weeks'], [1, '份面板分析', 'panel analysis'], [3, '组稳健性检验', 'robustness checks']],
    phases: {
      startZh: '高一，经济学夏校证书两张，没碰过一行数据。',
      startEn: 'Grade 10, two economics summer-school certificates, never touched a row of data.',
      diagZh: '知道概念，不知道概念怎么被检验。',
      diagEn: 'Knew the concepts; did not know how concepts get tested.',
      changeZh: '远程劳动经济学课题，任务是复现一篇已发表的最低工资研究，再加一组稳健性检验。',
      changeEn: 'A remote labour-economics project: reproduce a published minimum-wage study, then add robustness checks.',
      wrongZh: '复现结果和原文差了一个符号。花了五周找到原因——原文用了不同的行业分类。',
      wrongEn: 'Her reproduction disagreed with the paper by a sign. Five weeks to find why: a different industry classification.',
      outcomeZh: '那五周成了她文书的主体。录取多伦多大学。',
      outcomeEn: 'Those five weeks became the core of her essay. Admitted to Toronto.',
    },
  },
  {
    inst: 'imperial', level: 'ug', year: 2025, group: 'phys',
    fromZh: '北京 · A-Level · 高二启动', fromEn: 'Beijing · A-Level · started Grade 11',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '化学竞赛选手，习惯了"有标准答案"。一个催化剂筛选课题让他第一次面对没人知道答案的问题。',
    quoteEn: 'A chemistry olympiad competitor used to problems with answers. A catalyst-screening project confronted him for the first time with a question nobody could answer.',
    stats: [[16, '周', 'weeks'], [1, '份筛选数据', 'screening dataset'], [40, '次重复实验', 'repeat runs']],
    phases: {
      startZh: '化学竞赛国奖，实验室经验为零。',
      startEn: 'A national chemistry-olympiad award, zero laboratory experience.',
      diagZh: '解题能力强，但不会面对不确定性。',
      diagEn: 'Strong problem-solver, but had never faced uncertainty.',
      changeZh: '暑期在地进入催化实验室，做铜基催化剂的选择性筛选，四十次重复实验。',
      changeEn: 'On site over the summer in a catalysis laboratory: selectivity screening of copper catalysts, forty repeat runs.',
      wrongZh: '前十次实验数据全无规律。他以为自己做错了；导师说没有，这就是真实的样子。',
      wrongEn: 'The first ten runs showed no pattern at all. He assumed he had erred; the mentor said no — this is what it actually looks like.',
      outcomeZh: '筛选数据进了论文的一张表。录取帝国理工。',
      outcomeEn: 'His screening data became a table in the paper. Admitted to Imperial.',
    },
  },
  {
    inst: 'nus', level: 'ug', year: 2025, group: 'comp',
    fromZh: '新加坡 · 本地中学 · 高一启动', fromEn: 'Singapore · local secondary school · started Year 3',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '本地学生，本地大学，本地导师。这个案例的价值在于说明：不出国也能做真的。',
    quoteEn: 'Local student, local university, local mentor. The point of this file is that you do not have to go abroad to do something real.',
    stats: [[18, '个月', 'months'], [1, '份评测报告', 'benchmark report'], [1, '位本地导师', 'local mentor']],
    phases: {
      startZh: '新加坡本地中学，编程基础好，家里希望"去美国做科研"。',
      startEn: 'A Singapore secondary school, good programming foundations, a family hoping for “research in America”.',
      diagZh: '最好的导师就在本地，没必要跨半个地球。',
      diagEn: 'The best mentor was ten kilometres away; no need to cross half the planet.',
      changeZh: '进入一位本地教授的课题，做语言模型输出的事实一致性评测。',
      changeEn: 'Onto a local professor’s project on factual-consistency evaluation of language-model outputs.',
      wrongZh: '评测集第一版被指出标注标准不一致，重做。',
      wrongEn: 'The first evaluation set was found to have inconsistent labelling criteria; redone.',
      outcomeZh: '评测报告被课题组引用。录取新加坡国立大学。',
      outcomeEn: 'The benchmark report was cited by the group. Admitted to NUS.',
    },
  },
  {
    inst: 'ucla', level: 'ug', year: 2025, group: 'social',
    fromZh: '洛杉矶 · 美高 · 高二启动', fromEn: 'Los Angeles · US high school · started Grade 11',
    progZh: '本科', progEn: 'Undergraduate',
    quoteZh: '他想做城市研究。我们让他先在一个街区走满二十小时，再读理论。',
    quoteEn: 'He wanted urban studies. We had him walk one neighbourhood for twenty hours before reading any theory.',
    stats: [[20, '小时步行', 'hours walked'], [1, '张行为地图', 'behaviour map'], [12, '周', 'weeks']],
    phases: {
      startZh: '美高，对城市规划有兴趣，读过很多书，没出过门。',
      startEn: 'A US high school, interested in urban planning, widely read, never in the field.',
      diagZh: '理论很多，观察为零。',
      diagEn: 'Plenty of theory, zero observation.',
      changeZh: '一个公共空间使用行为的定点观察课题，先走，后画，再分析。',
      changeEn: 'A stationary-observation project on public-space use: walk first, draw, then analyse.',
      wrongZh: '第一版地图被导师指出全是"应该有什么"，没有"实际有什么"。',
      wrongEn: 'His first map was rejected as showing what should be there rather than what was.',
      outcomeZh: '一张行为地图进入课题组报告。录取 UCLA。',
      outcomeEn: 'A behaviour map entered the group’s report. Admitted to UCLA.',
    },
  },

  /* ================= 示例：硕士 ================= */
  {
    inst: 'yale', level: 'ms', year: 2026, group: 'comp',
    fromZh: '上海 · 985 本科 · 应用数学', fromEn: 'Shanghai · 985 university · Applied Mathematics',
    progZh: '统计与数据科学 · 硕士', progEn: 'Statistics & Data Science · MS',
    quoteZh: 'GPA 在班级中游。真正起作用的是一个教育数据上的因果推断项目——做得规范、写得诚实，连失败的部分也照实写了。',
    quoteEn: 'A mid-class GPA. What moved the file was a causal-inference project on education data — done properly and written up honestly, failures included.',
    stats: [[11, '个月', 'months'], [1, '篇预印本', 'preprint'], [3.4, 'GPA', 'GPA']],
    phases: {
      startZh: '数学基础扎实，GPA 3.4，没有任何科研。',
      startEn: 'Solid mathematics, GPA 3.4, no research at all.',
      diagZh: 'GPA 改不了，能改的是"有没有一件让人记住的事"。',
      diagEn: 'The GPA could not be changed; what could was whether there was one memorable thing.',
      changeZh: '远程因果推断课题，重做一篇已发表教育干预研究的分析。',
      changeEn: 'A remote causal-inference project re-analysing a published education intervention.',
      wrongZh: '复现失败——原文的效应在她的分析里消失了。她把这件事写进了预印本。',
      wrongEn: 'The reproduction failed — the published effect vanished in her analysis. She wrote that into the preprint.',
      outcomeZh: '一篇诚实的预印本。录取耶鲁统计硕士。',
      outcomeEn: 'An honest preprint. Admitted to Yale’s statistics master’s.',
    },
  },
  {
    inst: 'emory', level: 'ms', year: 2026, group: 'life',
    fromZh: '广州 · 临床医学本科', fromEn: 'Guangzhou · medical undergraduate',
    progZh: '公共卫生 · 硕士 · 奖学金', progEn: 'Public Health · MPH · Scholarship',
    quoteZh: '临床能力强，流行病学方向却单薄。一年国际公益组织的项目评估工作，补上了她档案里最缺的量化证据。',
    quoteEn: 'Clinically strong but epidemiologically thin. A year on an NGO programme-evaluation team supplied the quantitative evidence her file was missing.',
    stats: [[12, '个月', 'months'], [1, '份评估报告', 'evaluation report'], [4, '个 offer', 'offers']],
    phases: {
      startZh: '临床医学本科，见习经历丰富，从没处理过一份数据集。',
      startEn: 'A medical undergraduate with abundant clinical exposure and no experience of a dataset.',
      diagZh: '公共卫生硕士要的是量化能力，她的档案里没有。',
      diagEn: 'An MPH wants quantitative ability; her file showed none.',
      changeZh: '进入一个国际卫生公益组织的评估团队，负责一个筛查项目覆盖率的分析。',
      changeEn: 'Onto an international health NGO’s evaluation team, responsible for analysing a screening programme’s coverage.',
      wrongZh: '第一版报告被机构退回：结论超出了数据能支持的范围。',
      wrongEn: 'The first report was returned by the organisation: the conclusions exceeded what the data supported.',
      outcomeZh: '修订版进入机构公开报告。四个 offer，选了 Emory 的奖学金。',
      outcomeEn: 'The revised version entered the organisation’s published report. Four offers; she took Emory’s with a scholarship.',
    },
  },
  {
    inst: 'johns-hopkins', level: 'ms', year: 2026, group: 'eng',
    fromZh: '杭州 · 985 本科 · 生物医学工程', fromEn: 'Hangzhou · 985 university · Biomedical Engineering',
    progZh: '生物医学工程 · 硕士', progEn: 'Biomedical Engineering · MSE',
    quoteZh: '为一项医院合作搭建的影像分析流程，文档写得足够好——她离开后，临床团队仍在使用。',
    quoteEn: 'An imaging-analysis pipeline built for a hospital collaboration, documented well enough that the clinical team kept using it after she left.',
    stats: [[10, '个月', 'months'], [1, '个临床工具', 'clinical tool'], [3, '个 offer', 'offers']],
    phases: {
      startZh: '课程项目很多，没有一个被真实用户用过。',
      startEn: 'Many course projects, none ever used by a real user.',
      diagZh: '缺的是"交付给别人"的经历。',
      diagEn: 'What was missing was the experience of delivering to someone else.',
      changeZh: '远程神经影像分割课题，任务是让模型在另一家医院的数据上也能用。',
      changeEn: 'A remote neuroimaging-segmentation project: make the model work on another hospital’s data.',
      wrongZh: '跨中心泛化前两版全部失败，准确率掉了三成。',
      wrongEn: 'The first two attempts at cross-site generalisation failed; accuracy fell by thirty percent.',
      outcomeZh: '第三版被临床团队采用。录取霍普金斯。',
      outcomeEn: 'The third version was adopted by the clinical team. Admitted to Johns Hopkins.',
    },
  },
  {
    inst: 'cmu', level: 'ms', year: 2026, group: 'eng',
    fromZh: '香港 · 港校本科 · 设计', fromEn: 'Hong Kong · local university · Design',
    progZh: '人机交互 · 硕士', progEn: 'Human–Computer Interaction · MHCI',
    quoteZh: '设计专业出身，作品集很美，没有一件经过用户测试。十四周里她做了十四次测试。',
    quoteEn: 'A design graduate with a beautiful portfolio and not one piece that had been user-tested. In fourteen weeks she ran fourteen tests.',
    stats: [[14, '周', 'weeks'], [14, '次用户测试', 'user tests'], [1, '份测试报告', 'test report']],
    phases: {
      startZh: '设计本科，作品集精美，全部是"我觉得用户会这样用"。',
      startEn: 'A design degree, a polished portfolio, every piece premised on “I think users will use it this way”.',
      diagZh: 'HCI 项目看的是证据，不是审美。',
      diagEn: 'HCI programmes look for evidence, not taste.',
      changeZh: '远程辅助技术课题：为视障用户做语音导航界面，每周一次真实用户测试。',
      changeEn: 'A remote assistive-technology project: a voice-navigation interface for blind users, with a real user test every week.',
      wrongZh: '第一次测试，两位被试都没能完成任务。她哭了，然后重做。',
      wrongEn: 'In the first test neither participant completed the task. She cried, then rebuilt it.',
      outcomeZh: '第十四周的版本被两位被试独立完成。录取 CMU。',
      outcomeEn: 'The fourteenth-week version was completed independently by both participants. Admitted to CMU.',
    },
  },
  {
    inst: 'eth', level: 'ms', year: 2026, group: 'phys',
    fromZh: '武汉 · 985 本科 · 物理', fromEn: 'Wuhan · 985 university · Physics',
    progZh: '物理 · 硕士', progEn: 'Physics · MSc',
    quoteZh: '理论很好，从没摸过仪器。导师让他自己搭一台简易低温测量装置，他花了两个月，然后终于懂了噪声从哪来。',
    quoteEn: 'Excellent theory, never touched an instrument. The mentor had him build a rudimentary cryogenic rig; it took two months, and then he finally understood where noise comes from.',
    stats: [[20, '周', 'weeks'], [1, '台自制装置', 'home-built rig'], [1, '份噪声谱', 'noise spectrum']],
    phases: {
      startZh: '物理系前 5%，全部是理论课，一次实验课挂了。',
      startEn: 'Top 5% in physics, all theory, one failed laboratory course.',
      diagZh: '欧洲的硕士项目要看动手。',
      diagEn: 'European master’s programmes want to see hands.',
      changeZh: '暑期在地进入凝聚态实验室，先搭装置，再做二维材料的输运测量。',
      changeEn: 'On site over the summer in a condensed-matter laboratory: build the rig first, then transport measurements on 2D materials.',
      wrongZh: '装置第一版接地错误，数据全是 50 Hz 噪声。',
      wrongEn: 'The rig’s first version was grounded wrongly; the data was pure 50 Hz noise.',
      outcomeZh: '一份噪声表征文档。录取 ETH。',
      outcomeEn: 'A noise-characterisation document. Admitted to ETH.',
    },
  },
  {
    inst: 'usc', level: 'ms', year: 2026, group: 'comp',
    fromZh: '成都 · 985 本科 · 软件工程', fromEn: 'Chengdu · 985 university · Software Engineering',
    progZh: '计算机科学 · 硕士', progEn: 'Computer Science · MS',
    quoteZh: '课程很多，却没有一样是属于他自己的。一段机器人实验室的经历，产出了一个至今仍在课题组系统里运行的模块。',
    quoteEn: 'Plenty of coursework, nothing that belonged to him. A robotics laboratory placement produced a module still running in the group’s stack.',
    stats: [[8, '个月', 'months'], [1, '个并入模块', 'merged module'], [6, '个 offer', 'offers']],
    phases: {
      startZh: '软件工程，绩点不错，简历上是一串课程名。',
      startEn: 'Software engineering, decent grades, a résumé that was a list of course titles.',
      diagZh: '需要一件"被别人依赖"的东西。',
      diagEn: 'Needed one thing that other people depended on.',
      changeZh: '混合模式机器人课题：IMU 与视觉里程计的融合模块。',
      changeEn: 'A hybrid robotics project: an IMU–visual-odometry fusion module.',
      wrongZh: '模块第一次合并请求被拒，因为没有测试。',
      wrongEn: 'The first merge request was rejected: no tests.',
      outcomeZh: '第二次合并通过。六个 offer。',
      outcomeEn: 'The second merge went through. Six offers.',
    },
  },

  /* ================= 示例：博士 ================= */
  {
    inst: 'nus', level: 'phd', year: 2026, group: 'comp',
    fromZh: '内地 211 本科 · 计算机', fromEn: 'Mainland 211 university · Computer Science',
    progZh: '数据科学 · 博士 · 全奖', progEn: 'Data Science · PhD · Fully funded',
    quoteZh: '上一轮按学校投，两度被拒。改按导师检索，锁定三个课题组，逐一去信。',
    quoteEn: 'Two rejections applying school-first. Re-ran the search advisor-first, found three groups whose open problems matched his code, and wrote to them.',
    stats: [[2, '个申请季', 'cycles'], [3, '位导师沟通', 'advisors contacted'], [2, '个全奖', 'funded offers']],
    phases: {
      startZh: '211 本科，一篇水会议论文，上一季被拒。',
      startEn: 'A 211 university, one weak conference paper, rejected the previous cycle.',
      diagZh: '选校逻辑错了。博士录取是导师决定的。',
      diagEn: 'The school-selection logic was wrong. Doctoral admission is decided by advisors.',
      changeZh: '一个新的可远程课题，问题选在他想去的三个课题组的交集上。',
      changeEn: 'A new remote project, its question chosen at the intersection of the three groups he wanted.',
      wrongZh: '三封信两封没回。第三封回了。',
      wrongEn: 'Two of three letters went unanswered. The third replied.',
      outcomeZh: '两个全奖 offer。',
      outcomeEn: 'Two fully funded offers.',
    },
  },
  {
    inst: 'michigan', level: 'phd', year: 2025, group: 'eng',
    fromZh: '美国州立大学本科 · 生物医学工程', fromEn: 'US state university · Biomedical Engineering',
    progZh: '生物医学工程 · 博士 · 全奖', progEn: 'Biomedical Engineering · PhD · Fully funded',
    quoteZh: '本科学校普通，实验室经历只有一个学期。两个暑期的长线机构培养，同时补上了技术和那封信。',
    quoteEn: 'An ordinary undergraduate institution, one semester of laboratory experience. Two summers of institute-track work supplied both the technique and the letter.',
    stats: [[2, '个暑期', 'summers'], [1, '篇一作论文', 'first-author paper'], [3, '个博士 offer', 'PhD offers']],
    phases: {
      startZh: '州立大学，绩点 3.7，一个学期的实验室经历。',
      startEn: 'A state university, GPA 3.7, one semester in a laboratory.',
      diagZh: '没有能证明"能独立做研究"的东西。',
      diagEn: 'Nothing that demonstrated independent research.',
      changeZh: '两个暑期在同一位导师下做可穿戴传感器课题，第二年独立负责校正算法。',
      changeEn: 'Two summers under the same mentor on a wearable-sensor project, owning the correction algorithm in year two.',
      wrongZh: '第二年的算法在真实数据上失效，只在仿真里成功。',
      wrongEn: 'In year two the algorithm failed on real data, succeeding only in simulation.',
      outcomeZh: '改用实机数据重训，最终一篇一作论文。三个博士 offer。',
      outcomeEn: 'Retrained on hardware data; a first-author paper in the end. Three doctoral offers.',
    },
  },
  {
    inst: 'northwestern', level: 'phd', year: 2024, group: 'phys',
    fromZh: '天津 · 985 本科 · 材料', fromEn: 'Tianjin · 985 university · Materials',
    progZh: '材料科学 · 博士 · 全奖', progEn: 'Materials Science · PhD · Fully funded',
    quoteZh: '他的推荐信来自一位退回过他海报三次的导师。那封信写了三次退回的原因。',
    quoteEn: 'His recommendation came from a mentor who had rejected his poster three times. The letter described all three rejections.',
    stats: [[22, '周', 'weeks'], [3, '次海报退回', 'poster rejections'], [1, '封详细推荐信', 'detailed letter']],
    phases: {
      startZh: '材料本科，成绩好，一段"参观式"科研。',
      startEn: 'A materials undergraduate, good grades, one “tour-style” research experience.',
      diagZh: '需要一位敢说不的导师。',
      diagEn: 'Needed a mentor willing to say no.',
      changeZh: '在地进入一个薄膜课题组，做湿度稳定性筛选。',
      changeEn: 'On site in a thin-film group, doing humidity-stability screening.',
      wrongZh: '海报被退回三次：数据不够、图不对、结论过头。',
      wrongEn: 'The poster was returned three times: too little data, wrong figures, overreaching conclusions.',
      outcomeZh: '第四版放行。推荐信里写了前三次。全奖录取西北大学。',
      outcomeEn: 'The fourth version cleared. The letter recorded the first three. A fully funded place at Northwestern.',
    },
  },
];

module.exports.levels = {
  ug:  { zh: '本科去向', en: 'Undergraduate' },
  ms:  { zh: '硕士去向', en: 'Master’s' },
  phd: { zh: '博士去向', en: 'Doctoral' },
};
