/**
 * 学员去向（112 条）
 * [机构 slug, 项目中文, 项目英文, 学段, 年份, 备注]
 * 学段：ug 本科 · ms 硕士 · phd 博士
 * 备注：adm 录取 · full 全额奖学金 · schol 奖学金 · ed 提前录取 · direct 直博
 *
 * 前 6 条由客户提供；其余为示例条目，上线前替换为真实录取记录。
 */
module.exports = [
  /* ---------- 客户提供 ---------- */
  ['princeton',     '本科',                 'Undergraduate',                         'ug',  2026, 'adm',  true],
  ['princeton',     '本科',                 'Undergraduate',                         'ug',  2026, 'adm',  true],
  ['harvard',       '医学院 · 硕士',        'Harvard Medical School · Master’s',     'ms',  2026, 'adm',  true],
  ['berkeley',      '本科',                 'Undergraduate',                         'ug',  2026, 'adm',  true],
  ['washington',    '本科',                 'Undergraduate',                         'ug',  2026, 'adm',  true],
  ['buffalo',       '博士',                 'Doctoral',                              'phd', 2026, 'full', true],

  /* ---------- 2026 ---------- */
  ['stanford',      '材料科学 · 硕士',      'Materials Science · MS',                'ms',  2026, 'adm'],
  ['mit',           '计算科学与工程 · 硕士','Computational Science & Engineering · SM','ms', 2026, 'adm'],
  ['yale',          '统计与数据科学 · 硕士','Statistics & Data Science · MS',        'ms',  2026, 'adm'],
  ['columbia',      '生物统计 · 硕士',      'Biostatistics · MS',                    'ms',  2026, 'schol'],
  ['johns-hopkins', '生物医学工程 · 硕士',  'Biomedical Engineering · MSE',          'ms',  2026, 'adm'],
  ['cornell',       '生物工程 · 本科',      'Biological Engineering · BS',           'ug',  2026, 'ed'],
  ['emory',         '公共卫生 · 硕士',      'Public Health · MPH',                   'ms',  2026, 'schol'],
  ['usc',           '计算机科学 · 硕士',    'Computer Science · MS',                 'ms',  2026, 'adm'],
  ['florida',       '环境工程 · 本科',      'Environmental Engineering · BS',        'ug',  2026, 'schol'],
  ['hku',           '内外全科医学 · 本科',  'Medicine · MBBS',                       'ug',  2026, 'adm'],
  ['nus',           '数据科学 · 博士',      'Data Science · PhD',                    'phd', 2026, 'full'],
  ['ntu',           '材料科学 · 本科',      'Materials Science · BEng',              'ug',  2026, 'adm'],
  ['ucla',          '本科',                 'Undergraduate',                         'ug',  2026, 'adm'],
  ['ucsd',          '生物信息 · 硕士',      'Bioinformatics · MS',                   'ms',  2026, 'adm'],
  ['michigan',      '本科',                 'Undergraduate',                         'ug',  2026, 'adm'],
  ['duke',          '环境管理 · 硕士',      'Environmental Management · MEM',        'ms',  2026, 'schol'],
  ['cmu',           '人机交互 · 硕士',      'Human–Computer Interaction · MHCI',     'ms',  2026, 'adm'],
  ['upenn',         '本科',                 'Undergraduate',                         'ug',  2026, 'ed'],
  ['toronto',       '经济学 · 硕士',        'Economics · MA',                        'ms',  2026, 'adm'],
  ['imperial',      '化学工程 · 硕士',      'Chemical Engineering · MSc',            'ms',  2026, 'adm'],
  ['ucl',           '认知神经科学 · 硕士',  'Cognitive Neuroscience · MSc',          'ms',  2026, 'adm'],
  ['eth',           '物理 · 硕士',          'Physics · MSc',                         'ms',  2026, 'adm'],
  ['hkust',         '机器人 · 博士',        'Robotics · PhD',                        'phd', 2026, 'full'],
  ['polyu',         '计算 · 博士',          'Computing · PhD',                       'phd', 2026, 'full'],
  ['georgia-tech',  '机械工程 · 本科',      'Mechanical Engineering · BS',           'ug',  2026, 'adm'],
  ['wisconsin',     '本科',                 'Undergraduate',                         'ug',  2026, 'schol'],
  ['illinois',      '电子与计算机工程 · 本科','Electrical & Computer Engineering · BS','ug', 2026, 'adm'],
  ['purdue',        '农业工程 · 本科',      'Agricultural Engineering · BS',         'ug',  2026, 'schol'],
  ['boston-u',      '本科',                 'Undergraduate',                         'ug',  2026, 'adm'],
  ['nyu',           '数据科学 · 硕士',      'Data Science · MS',                     'ms',  2026, 'adm'],
  ['rice',          '化学 · 博士',          'Chemistry · PhD',                       'phd', 2026, 'full'],
  ['melbourne',     '本科',                 'Undergraduate',                         'ug',  2026, 'adm'],

  /* ---------- 2025 ---------- */
  ['harvard',       '免疫学 · 博士',        'Immunology · PhD',                      'phd', 2025, 'full'],
  ['princeton',     '分子生物学 · 博士',    'Molecular Biology · PhD',               'phd', 2025, 'direct'],
  ['berkeley',      '电子工程与计算机 · 硕士','EECS · MEng',                         'ms',  2025, 'adm'],
  ['stanford',      '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['yale',          '本科',                 'Undergraduate',                         'ug',  2025, 'ed'],
  ['columbia',      '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['chicago',       '经济学 · 本科',        'Economics · BA',                        'ug',  2025, 'ed'],
  ['cornell',       '计算机科学 · 硕士',    'Computer Science · MEng',               'ms',  2025, 'adm'],
  ['upenn',         '生物工程 · 硕士',      'Bioengineering · MSE',                  'ms',  2025, 'adm'],
  ['northwestern',  '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['duke',          '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['johns-hopkins', '公共卫生 · 硕士',      'Public Health · MPH',                   'ms',  2025, 'schol'],
  ['emory',         '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['vanderbilt',    '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['brown',         '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['ucla',          '统计 · 硕士',          'Statistics · MS',                       'ms',  2025, 'adm'],
  ['ucsd',          '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['washington',    '计算机科学 · 硕士',    'Computer Science · MS',                 'ms',  2025, 'adm'],
  ['michigan',      '生物医学工程 · 博士',  'Biomedical Engineering · PhD',          'phd', 2025, 'full'],
  ['cmu',           '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['georgia-tech',  '计算机科学 · 硕士',    'Computer Science · MS',                 'ms',  2025, 'adm'],
  ['ut-austin',     '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['unc',           '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['usc',           '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['florida',       '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['george-mason',  '数据分析 · 硕士',      'Data Analytics · MS',                   'ms',  2025, 'schol'],
  ['buffalo',       '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['toronto',       '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['ubc',           '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['mcgill',        '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['oxford',        '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['cambridge',     '自然科学 · 本科',      'Natural Sciences · BA',                 'ug',  2025, 'adm'],
  ['imperial',      '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['ucl',           '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['edinburgh',     '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['lse',           '经济学 · 本科',        'Economics · BSc',                       'ug',  2025, 'adm'],
  ['epfl',          '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['tu-delft',      '土木工程 · 硕士',      'Civil Engineering · MSc',               'ms',  2025, 'adm'],
  ['hku',           '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['cuhk',          '生物医学 · 本科',      'Biomedical Sciences · BSc',             'ug',  2025, 'adm'],
  ['hkust',         '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['cityu',         '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['nus',           '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['ntu',           '电子工程 · 硕士',      'Electrical Engineering · MSc',          'ms',  2025, 'adm'],
  ['sydney',        '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],
  ['anu',           '本科',                 'Undergraduate',                         'ug',  2025, 'schol'],
  ['tokyo',         '本科',                 'Undergraduate',                         'ug',  2025, 'adm'],

  /* ---------- 2024 ---------- */
  ['mit',           '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['stanford',      '计算机科学 · 硕士',    'Computer Science · MS',                 'ms',  2024, 'adm'],
  ['harvard',       '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['princeton',     '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['berkeley',      '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['yale',          '公共卫生 · 硕士',      'Public Health · MPH',                   'ms',  2024, 'schol'],
  ['columbia',      '数据科学 · 硕士',      'Data Science · MS',                     'ms',  2024, 'adm'],
  ['cornell',       '本科',                 'Undergraduate',                         'ug',  2024, 'ed'],
  ['upenn',         '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['chicago',       '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['johns-hopkins', '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['northwestern',  '材料科学 · 博士',      'Materials Science · PhD',               'phd', 2024, 'full'],
  ['duke',          '统计 · 硕士',          'Statistics · MS',                       'ms',  2024, 'adm'],
  ['emory',         '公共卫生 · 硕士',      'Public Health · MPH',                   'ms',  2024, 'schol'],
  ['ucla',          '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['washington',    '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['michigan',      '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['georgia-tech',  '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['florida',       '生物医学工程 · 硕士',  'Biomedical Engineering · MS',           'ms',  2024, 'schol'],
  ['george-mason',  '本科',                 'Undergraduate',                         'ug',  2024, 'schol'],
  ['georgia-state', '本科',                 'Undergraduate',                         'ug',  2024, 'schol'],
  ['toronto',       '计算机科学 · 硕士',    'Computer Science · MSc',                'ms',  2024, 'adm'],
  ['oxford',        '统计 · 硕士',          'Statistical Science · MSc',             'ms',  2024, 'adm'],
  ['cambridge',     '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['imperial',      '机械工程 · 本科',      'Mechanical Engineering · MEng',         'ug',  2024, 'adm'],
  ['eth',           '计算机科学 · 硕士',    'Computer Science · MSc',                'ms',  2024, 'adm'],
  ['hku',           '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['cuhk',          '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['polyu',         '本科',                 'Undergraduate',                         'ug',  2024, 'schol'],
  ['nus',           '化学 · 博士',          'Chemistry · PhD',                       'phd', 2024, 'full'],
  ['ntu',           '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['melbourne',     '本科',                 'Undergraduate',                         'ug',  2024, 'adm'],
  ['kaist',         '本科',                 'Undergraduate',                         'ug',  2024, 'schol'],
];

module.exports.levels = {
  ug:  { zh: '本科', en: 'Undergraduate' },
  ms:  { zh: '硕士', en: 'Master’s' },
  phd: { zh: '博士', en: 'Doctoral' },
};
module.exports.notes = {
  adm:    { zh: '录取',       en: 'Admitted' },
  full:   { zh: '全额奖学金', en: 'Full funding' },
  schol:  { zh: '奖学金',     en: 'Scholarship' },
  ed:     { zh: '提前录取',   en: 'Early decision' },
  direct: { zh: '直博',       en: 'Direct PhD' },
};
