/**
 * 导师阵容（25 位）
 * 前 5 位的姓氏与任职机构由客户提供；其余为示例条目，上线前替换为真实导师。
 * 每位：style（带教习惯）/ work（课题类型）/ rule（硬性规矩）三段，避免同质化。
 *
 * group 用于筛选：life 生命与医学 · eng 工程 · comp 计算与数据 · phys 物理与化学 · env 环境与地球 · social 社科与人文
 */
module.exports = [
  /* ================= 生命与医学 ================= */
  {
    id: 'huang', group: 'life', real: true,
    zh: '黄教授', en: 'Prof. Huang', inst: 'emory',
    fieldZh: '公共卫生 · 免疫学', fieldEn: 'Public Health & Immunology',
    styleZh: '新学员进组的头两到三个月，任务只有读文献和跟组会。家长常在这个阶段打电话问「是不是什么都没做」，她的回答一向是同一句：一个读不懂文献还假装读懂了的学生，后面做什么都是假的。',
    styleEn: 'For the first two or three months a new student does nothing but read and attend group meetings. Parents often call to ask whether anything is happening; her answer never changes: a student who cannot read a paper and pretends otherwise will be faking everything that comes after.',
    workZh: '课题多在免疫学与公共卫生的交界——疫苗接种后的抗体动态、社区筛查的覆盖缺口——既有湿实验也有大量数据工作，学生可以按自己的时间条件选路径。',
    workEn: 'Projects sit at the boundary of immunology and public health — antibody dynamics after vaccination, coverage gaps in community screening — combining bench work with substantial data analysis, so students can choose a path that fits their calendar.',
    ruleZh: '结项时必须能独立复现自己的全部结果。做不到就不出评价信，这一条她从未松口。',
    ruleEn: 'Every student must be able to reproduce all of their own results independently at the end. No reproduction, no evaluation letter. She has never once relaxed this.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '在地 / 远程', modeEn: 'On-site or remote', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'chen', group: 'life',
    zh: '陈教授', en: 'Prof. Chen', inst: 'johns-hopkins',
    fieldZh: '神经科学 · 行为', fieldEn: 'Neuroscience & Behaviour',
    styleZh: '他给每个学生的第一个任务是设计一个行为实验，然后亲自把它做砸——不是恶意，是让学生在第一周就见到「对照组没设好」长什么样。',
    styleEn: 'The first task he gives every student is to design a behavioural experiment; then he personally runs it badly — not out of malice, but so the student sees in week one what a poorly set control looks like.',
    workZh: '小鼠行为范式与神经环路成像。学生通常从视频标注与行为评分起步，做得好的会进入成像数据分析。',
    workEn: 'Mouse behavioural paradigms and circuit imaging. Students typically start with video annotation and behavioural scoring; the good ones progress to imaging analysis.',
    ruleZh: '实验记录本每周检查一次。记录写得含糊的那周，不算工时。',
    ruleEn: 'Laboratory notebooks are checked weekly. A week with vague entries does not count as hours worked.',
    spec: { places: 2, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'wang', group: 'life',
    zh: '王教授', en: 'Prof. Wang', inst: 'washington',
    fieldZh: '计算生物学 · 基因组', fieldEn: 'Computational Biology & Genomics',
    styleZh: '她不接受任何「跑通了」作为进度汇报。学生必须说清跑通的是哪一步、参数为什么这样选、换一批数据会不会崩。',
    styleEn: 'She does not accept “it ran” as a progress report. The student must say which step ran, why those parameters, and whether it would break on a different batch.',
    workZh: '单细胞测序分析与基因调控网络推断。全程计算，可远程，对编程基础有明确要求。',
    workEn: 'Single-cell sequencing analysis and gene regulatory network inference. Entirely computational and remote-eligible, with an explicit programming prerequisite.',
    ruleZh: '所有代码进课题组的版本库，提交记录里有学生自己的名字。这既是训练，也是证据。',
    ruleEn: 'All code goes into the group’s repository under the student’s own name. It is both training and evidence.',
    spec: { places: 3, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'hu', group: 'life',
    zh: '胡教授', en: 'Prof. Hu', inst: 'cuhk',
    fieldZh: '临床流行病学', fieldEn: 'Clinical Epidemiology',
    styleZh: '他习惯让学生先读一篇被撤稿的论文，再读同一课题的正确版本。他说这比讲十节统计课都管用。',
    styleEn: 'He has students read a retracted paper first, then the correct version on the same topic. He says it does more than ten lectures on statistics.',
    workZh: '基于真实队列的临床数据分析：随访数据清洗、混杂因素控制、生存分析。适合志在医学的学生。',
    workEn: 'Clinical data analysis on real cohorts: follow-up data cleaning, confounder control, survival analysis. Suited to students heading toward medicine.',
    ruleZh: '数据脱敏协议签署前，学生不接触任何一行数据。这条没有例外。',
    ruleEn: 'No student touches a single row of data before signing the de-identification protocol. No exceptions.',
    spec: { places: 2, stageZh: '本科 · 医学预科', stageEn: 'Undergraduate · pre-med', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'wu', group: 'life',
    zh: '吴教授', en: 'Prof. Wu', inst: 'ucl',
    fieldZh: '认知心理学', fieldEn: 'Cognitive Psychology',
    styleZh: '她要求学生在预注册平台上先公开实验假设，再收数据。她的原话：「先想好你要怎么输，才知道你有没有赢。」',
    styleEn: 'She requires students to pre-register hypotheses publicly before collecting data. Her phrase: “Decide how you would lose before you can know whether you won.”',
    workZh: '注意力与记忆的行为实验，线上被试招募与实验程序编写。学生能独立完成从设计到分析的完整闭环。',
    workEn: 'Behavioural experiments on attention and memory, with online participant recruitment and experiment programming. Students complete the full loop from design to analysis.',
    ruleZh: '任何未预注册的分析，结果里必须标明「探索性」。',
    ruleEn: 'Any analysis not pre-registered must be labelled “exploratory” in the results.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 工程 ================= */
  {
    id: 'yang', group: 'eng', real: true,
    zh: '杨教授', en: 'Prof. Yang', inst: 'florida',
    fieldZh: '生物医学工程 · 环境工程', fieldEn: 'Biomedical & Environmental Engineering',
    styleZh: '他不太写长评语，但会把学生做的每一版原型编号存档。到结项时那一串编号本身就是最有说服力的记录：第一版失败在哪里、第七版改了什么。',
    styleEn: 'He does not write long commentary, but he archives and numbers every prototype a student produces. By the end, that numbered sequence is the most persuasive record there is: where version one failed, what changed by version seven.',
    workZh: '可穿戴传感器的信号校正、灌溉水中微塑料的沉降实验、器件原型的反复迭代。评判标准很工程师：东西能不能用，重复几次还一不一样。',
    workEn: 'Signal correction for wearable sensors, settling experiments for microplastics in irrigation water, prototype devices iterated again and again. An engineer’s standard: does it work, and does it still hold after you repeat it.',
    ruleZh: '湿实验与器件加工没法远程。适合能安排整段暑期、或就近的学生。',
    ruleEn: 'Bench work and fabrication cannot be done remotely. Suited to students who can commit a full summer, or who are nearby.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '以在地为主', modeEn: 'Primarily on-site', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'lin', group: 'eng',
    zh: '林教授', en: 'Prof. Lin', inst: 'hkust',
    fieldZh: '机器人 · 控制', fieldEn: 'Robotics & Control',
    styleZh: '他的组会有一条奇怪的规矩：演示必须用实机，不许放仿真视频。他说仿真里什么都能成功，招生官也知道这一点。',
    styleEn: 'His group meetings have an odd rule: demos must run on real hardware, never a simulation video. Everything succeeds in simulation, he says, and admissions committees know it.',
    workZh: '四足与机械臂的运动控制、传感器融合。学生从标定与数据采集起步，能力够的进入控制算法调参。',
    workEn: 'Locomotion control for quadrupeds and manipulators, sensor fusion. Students begin with calibration and data capture; capable ones move into controller tuning.',
    ruleZh: '进实验室前必须通过安全考核。摔坏一台机器人的成本，够付半年学费。',
    ruleEn: 'Safety certification before entering the lab. Breaking one robot costs half a year’s tuition.',
    spec: { places: 2, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'zhang', group: 'eng',
    zh: '张教授', en: 'Prof. Zhang', inst: 'georgia-tech',
    fieldZh: '机械工程 · 能源系统', fieldEn: 'Mechanical Engineering & Energy Systems',
    styleZh: '每个学生入组第一周要做一件事：把上一位学生留下的实验装置拆开，画出原理图，再装回去。装不回去的也有——他说那正好是学习的开始。',
    styleEn: 'Every student’s first week: dismantle the apparatus left by the previous student, draw the schematic, reassemble it. Some cannot reassemble it — which, he says, is precisely where learning begins.',
    workZh: '热管理与储能系统的实验测试，含大量传感器布置与数据采集。适合动手能力强的学生。',
    workEn: 'Experimental testing of thermal management and energy-storage systems, heavy on sensor placement and data acquisition. For students who like to build.',
    ruleZh: '所有测量数据必须附不确定度。没有误差棒的图，组会上不许放。',
    ruleEn: 'Every measurement must carry an uncertainty. A figure without error bars is not shown in group meeting.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'he', group: 'eng',
    zh: '何教授', en: 'Prof. He', inst: 'ntu',
    fieldZh: '电子工程 · 光子学', fieldEn: 'Electrical Engineering & Photonics',
    styleZh: '她要求学生用三句话向非专业人士解释自己的课题，说不清楚就回去重读。她说如果你解释不了，你就还没真的懂。',
    styleEn: 'She makes students explain their project in three sentences to a non-specialist; if they cannot, they go back and reread. If you cannot explain it, she says, you do not yet understand it.',
    workZh: '集成光子器件的仿真与表征。学生前期做仿真（可远程），后期进洁净室做测试。',
    workEn: 'Simulation and characterisation of integrated photonic devices. Early-stage simulation can be remote; later testing is in the cleanroom.',
    ruleZh: '仿真结果必须与至少一组实测数据对得上，否则不进报告。',
    ruleEn: 'Simulation results must agree with at least one set of measured data before they enter a report.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'han', group: 'eng',
    zh: '韩教授', en: 'Prof. Han', inst: 'cmu',
    fieldZh: '人机交互', fieldEn: 'Human–Computer Interaction',
    styleZh: '他的学生每周必须做一次真实用户测试，哪怕只有两个被试。他说设计师最大的错觉是「我觉得用户会这样用」。',
    styleEn: 'His students run a real user test every week, even with only two participants. A designer’s greatest illusion, he says, is “I think users will use it this way.”',
    workZh: '辅助技术与可访问性研究：为视障或行动不便用户设计交互原型。既有编程也有田野观察。',
    workEn: 'Assistive technology and accessibility: interaction prototypes for visually impaired or mobility-limited users. Both programming and field observation.',
    ruleZh: '用户测试必须有知情同意记录。没有的，数据作废。',
    ruleEn: 'User tests require documented informed consent. Without it, the data is discarded.',
    spec: { places: 3, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 计算与数据 ================= */
  {
    id: 'zhao', group: 'comp', real: true,
    zh: '赵教授', en: 'Prof. Zhao', inst: 'george-mason',
    fieldZh: '数据科学 · 公共政策', fieldEn: 'Data Science & Public Policy',
    styleZh: '他对学生的第一项训练不是建模，而是把一个含糊的社会问题改写成一个可被数据回答的问题。这一步通常要反复四五轮。很多学生第一次交上来的选题，他的批注只有一句：「这个问题没有答案，因为它没有被问清楚。」',
    styleEn: 'The first thing he trains a student to do is not modelling but rewriting a vague social question into one that data can answer. This usually takes four or five rounds. On a first attempt his annotation is often one line: “This question has no answer, because it has not been asked clearly.”',
    workZh: '政策数据分析：教育经费改革的断点回归、通勤数据里的居住隔离指标、城市热岛与急诊量的关联。承担了我们绝大部分可远程课题。',
    workEn: 'Policy data analysis: regression discontinuity on school-funding reform, segregation indices from commuting data, urban heat and emergency admissions. He carries most of our remote-eligible projects.',
    ruleZh: '代码必须附 README 和完整复现步骤，否则不算交付。',
    ruleEn: 'Code must ship with a README and complete reproduction steps, or it is not accepted as delivered.',
    spec: { places: 4, stageZh: '高一起 · 本科', stageEn: 'Grade 10 up · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'li-polyu', group: 'comp', real: true,
    zh: '李教授', en: 'Prof. Li', inst: 'polyu',
    fieldZh: '电子计算 · 人工智能', fieldEn: 'Computing & Artificial Intelligence',
    styleZh: '每年只接收两名中学生，多一个都不接。理由很直白：三年连续带教，他能记住的学生就这么多；记不住的学生，他写不出有细节的推荐信。',
    styleEn: 'He takes exactly two secondary students a year, never three. His reason is blunt: over three years, two is the number he can genuinely remember, and he cannot write a detailed letter about a student he does not remember.',
    workZh: '长线培养主力导师。第一年文献与工具，第二年独立负责子问题，第三年才谈产出。课题为计算方向，可远程，时区与内地相近。',
    workEn: 'The backbone of our institute track: year one is literature and tooling, year two an owned sub-question, output not discussed until year three. Computational, remote-eligible, in a time zone close to the mainland.',
    ruleZh: '中途不换导师。换了，三年的记忆就断了。',
    ruleEn: 'No change of mentor mid-track. A change breaks three years of memory.',
    spec: { places: 2, stageZh: '中学长线为主', stageEn: 'Secondary, long track', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '2 – 3 年', minEn: '2 – 3 years' },
  },
  {
    id: 'zhou', group: 'comp',
    zh: '周教授', en: 'Prof. Zhou', inst: 'columbia',
    fieldZh: '统计学 · 因果推断', fieldEn: 'Statistics & Causal Inference',
    styleZh: '她让学生先用一份已经发表的数据，重做一遍作者的分析。对上了，再开始自己的课题；对不上，先搞清楚为什么——这一步常常就是一篇论文。',
    styleEn: 'She has students re-run a published author’s analysis on the published data first. If it matches, they begin their own project; if not, they find out why — and that alone is often a paper.',
    workZh: '准实验方法在教育与医疗数据上的应用。全计算，可远程，数学基础要求高。',
    workEn: 'Quasi-experimental methods applied to education and health data. Fully computational, remote-eligible, mathematically demanding.',
    ruleZh: '每份分析必须写明「这个结论在什么假设下才成立」。没有这段，稿子退回。',
    ruleEn: 'Every analysis must state the assumptions under which the conclusion holds. Without that paragraph, the draft is returned.',
    spec: { places: 3, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'xie', group: 'comp',
    zh: '谢教授', en: 'Prof. Xie', inst: 'cambridge',
    fieldZh: '应用数学', fieldEn: 'Applied Mathematics',
    styleZh: '他从不直接给答案，只给下一本要读的书。有学生统计过，一个学期他推荐了 23 本，读完 6 本，课题做完了。',
    styleEn: 'He never gives answers, only the next book to read. One student counted: 23 recommendations in a term, 6 actually read, project completed.',
    workZh: '偏微分方程的数值方法与流体建模。学生用代码验证理论，理论指导代码——两边都不能偏废。',
    workEn: 'Numerical methods for PDEs and fluid modelling. Students verify theory with code and let theory guide the code — neither side may be neglected.',
    ruleZh: '推导必须手写。他不看打字的数学。',
    ruleEn: 'Derivations must be handwritten. He does not read typed mathematics.',
    spec: { places: 1, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'tang', group: 'comp',
    zh: '唐教授', en: 'Prof. Tang', inst: 'ubc',
    fieldZh: '学习科学 · 教育数据', fieldEn: 'Learning Sciences & Education Data',
    styleZh: '她的学生要先当一个月助教，观察真实课堂，然后才允许碰数据。她说没见过教室的人分析不了教育数据。',
    styleEn: 'Her students spend a month as teaching assistants observing real classrooms before touching data. Someone who has never seen a classroom, she says, cannot analyse education data.',
    workZh: '在线学习平台的行为数据分析，学习路径与成绩的关联。可远程，对高中生尤其友好。',
    workEn: 'Behavioural data from online learning platforms, linking learning paths to outcomes. Remote-eligible and especially accessible to secondary students.',
    ruleZh: '涉及未成年人数据的分析，每一步都要过伦理审查。慢，但没有捷径。',
    ruleEn: 'Every analysis involving minors’ data passes ethics review at each step. Slow, and without shortcuts.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 物理与化学 ================= */
  {
    id: 'li-nus', group: 'phys', real: true,
    zh: '李教授', en: 'Prof. Lee', inst: 'nus',
    fieldZh: '化学 · 材料科学', fieldEn: 'Chemistry & Materials Science',
    styleZh: '在我们的导师里，他是最常说「不」的那一位。他明确保留拒绝为不达标工作背书的权利，并且真的用过——有学员的海报被退回三次，第四次才放行；也有学员最终没有拿到他的评价信。',
    styleEn: 'Among our faculty he is the one who says no most often. He retains the right to decline to endorse work that is not good enough, and has used it — one poster was sent back three times before he cleared it; another student finished without his letter.',
    workZh: '钙钛矿薄膜、高分子自组装这类材料工作，以在地湿实验为主，对动手能力要求高。',
    workEn: 'Perovskite thin films and polymer self-assembly — primarily on-site bench work, demanding in practical skill.',
    ruleZh: '这条写进了与他的约定，也写进了与家庭的合同：如果一位导师从不拒绝，那他的认可就不值钱。',
    ruleEn: 'Written into our agreement with him and our contract with families: a mentor who never refuses has an endorsement worth nothing.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '在地湿实验', modeEn: 'On-site, wet lab', minZh: '18 周', minEn: '18 weeks' },
  },
  {
    id: 'ma', group: 'phys',
    zh: '马教授', en: 'Prof. Ma', inst: 'eth',
    fieldZh: '凝聚态物理 · 量子材料', fieldEn: 'Condensed Matter & Quantum Materials',
    styleZh: '他让学生自己搭一台简易的低温测量装置，哪怕实验室里有现成的。他说用别人的仪器得到的数据，你解释不了噪声从哪来。',
    styleEn: 'He has students build their own rudimentary low-temperature measurement rig even though the lab has a proper one. With someone else’s instrument, he says, you cannot explain where the noise comes from.',
    workZh: '二维材料的输运测量与数据分析。前期可远程做数据处理，后期需在地做测量。',
    workEn: 'Transport measurements on two-dimensional materials and analysis. Early data work can be remote; measurements later are on site.',
    ruleZh: '每个数据点必须能追溯到原始文件与测量时间。',
    ruleEn: 'Every data point must trace back to a raw file and a timestamp.',
    spec: { places: 1, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'xu', group: 'phys',
    zh: '徐教授', en: 'Prof. Xu', inst: 'imperial',
    fieldZh: '化学工程 · 催化', fieldEn: 'Chemical Engineering & Catalysis',
    styleZh: '她要求学生在每次实验前写下预期结果，实验后对照。她说科研的乐趣不在于猜对，在于搞清楚为什么猜错。',
    styleEn: 'She has students write the expected result before every experiment and compare afterwards. The pleasure of research, she says, is not in guessing right but in understanding why you guessed wrong.',
    workZh: '催化剂筛选与反应条件优化，含大量重复实验与数据整理。适合耐心好、手稳的学生。',
    workEn: 'Catalyst screening and reaction-condition optimisation, with a great deal of repetition and data curation. For patient students with steady hands.',
    ruleZh: '未经安全培训不得单独操作。培训要考试，不及格重考。',
    ruleEn: 'No unsupervised bench work without safety training, which is examined and retaken on failure.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'liu', group: 'phys',
    zh: '刘教授', en: 'Prof. Liu', inst: 'ucsd',
    fieldZh: '海洋科学 · 气候物理', fieldEn: 'Ocean Science & Climate Physics',
    styleZh: '他带学生出过一次海，回来后学生对「数据质量」有了完全不同的理解——晕船的时候记录的数据，可信度是要打折的。',
    styleEn: 'He took students to sea once; they came back with a very different understanding of data quality — readings logged while seasick deserve a discount.',
    workZh: '海洋观测数据的处理与气候模式的对比分析。以计算为主，可远程；偶有出海机会。',
    workEn: 'Processing ocean observations and comparing them against climate models. Mainly computational and remote; occasional opportunities at sea.',
    ruleZh: '所有图的坐标轴必须带单位。他说这条规矩救过他三篇论文。',
    ruleEn: 'Every axis on every figure carries a unit. This rule, he says, has saved three of his papers.',
    spec: { places: 2, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },

  /* ================= 环境与地球 ================= */
  {
    id: 'gao', group: 'env',
    zh: '高教授', en: 'Prof. Gao', inst: 'duke',
    fieldZh: '生态学 · 环境科学', fieldEn: 'Ecology & Environmental Science',
    styleZh: '田野采样期间，她要求学生每天写一页手记，记的不是数据，是「今天哪里可能出错了」。这些手记后来成了论文里最诚实的一段。',
    styleEn: 'During field sampling she requires a one-page daily note — not data, but “where might I have gone wrong today”. Those notes later become the most honest paragraph in the paper.',
    workZh: '湿地生态监测与水质分析，有田野季也有实验室季。适合不怕晒、不怕虫的学生。',
    workEn: 'Wetland ecological monitoring and water-quality analysis, with a field season and a laboratory season. For students who mind neither sun nor insects.',
    ruleZh: '田野安全培训是硬门槛。没有例外，包括她自己。',
    ruleEn: 'Field safety training is mandatory — including for her.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '在地为主', modeEn: 'Primarily on-site', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'luo', group: 'env',
    zh: '罗教授', en: 'Prof. Luo', inst: 'purdue',
    fieldZh: '农业科学 · 食品系统', fieldEn: 'Agricultural Science & Food Systems',
    styleZh: '他的学生第一天领到的不是文献，是一块试验田。他说农学的所有问题最后都要回到地里去验证。',
    styleEn: 'On day one his students receive not a reading list but a plot of experimental land. Every question in agronomy, he says, ends up being tested in the ground.',
    workZh: '作物表型数据采集、无人机影像分析、土壤指标监测。计算与田野各半。',
    workEn: 'Crop phenotyping, drone imagery analysis, soil monitoring. Half computational, half field.',
    ruleZh: '田间记录必须当天录入，隔夜的记忆不算数据。',
    ruleEn: 'Field notes are entered the same day. Memory from the night before is not data.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'liang', group: 'env',
    zh: '梁教授', en: 'Prof. Leung', inst: 'hku',
    fieldZh: '城市规划 · 建成环境', fieldEn: 'Urban Planning & Built Environment',
    styleZh: '他让学生先在一个街区走满 20 个小时，画出来，再开始读任何规划理论。他说地图是走出来的，不是画出来的。',
    styleEn: 'Students walk one neighbourhood for twenty hours and draw it before reading any planning theory. A map, he says, is walked, not drawn.',
    workZh: '城市热岛、步行可达性、社区空间使用的实地调研与空间分析。GIS 与田野结合。',
    workEn: 'Urban heat, walkability and community space use — fieldwork combined with spatial analysis in GIS.',
    ruleZh: '所有调研必须有人在场记录，不接受纯遥感或纯问卷。',
    ruleEn: 'All surveys require an observer physically present. Pure remote sensing or pure questionnaires are not accepted.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '在地为主', modeEn: 'Primarily on-site', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 社科与人文 ================= */
  {
    id: 'zheng', group: 'social',
    zh: '郑教授', en: 'Prof. Zheng', inst: 'toronto',
    fieldZh: '劳动经济学', fieldEn: 'Labour Economics',
    styleZh: '她的组会不讨论结果，只讨论识别策略：你凭什么说这是因果，而不是相关？回答不了这个问题的分析，不管结果多好看都不进报告。',
    styleEn: 'Her group meetings do not discuss results, only identification: on what grounds is this causal rather than correlational? An analysis that cannot answer stays out of the report, however pretty the result.',
    workZh: '最低工资、移民与就业的面板数据分析。全计算，可远程。',
    workEn: 'Panel-data analysis of minimum wage, migration and employment. Fully computational, remote-eligible.',
    ruleZh: '所有回归都要报告稳健性检验。一个模型就下结论的，退回重做。',
    ruleEn: 'Every regression reports robustness checks. A conclusion from a single model is sent back.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'sun', group: 'social',
    zh: '孙教授', en: 'Prof. Sun', inst: 'michigan',
    fieldZh: '社会学 · 城市与不平等', fieldEn: 'Sociology, Cities & Inequality',
    styleZh: '他要求学生在做定量分析前先做十次深度访谈。他说数字告诉你「是什么」，访谈告诉你「为什么」，两个都没有的研究是瞎的。',
    styleEn: 'Ten in-depth interviews before any quantitative work. Numbers tell you what, he says; interviews tell you why; research with neither is blind.',
    workZh: '住房、教育资源分布与社会流动的混合方法研究。适合愿意跟人打交道的学生。',
    workEn: 'Mixed-methods research on housing, educational resources and social mobility. For students willing to talk to people.',
    ruleZh: '访谈录音必须逐字转录，由学生自己完成。转录是研究的一部分。',
    ruleEn: 'Interview recordings are transcribed verbatim by the student. Transcription is part of the research.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'song', group: 'social',
    zh: '宋教授', en: 'Prof. Song', inst: 'lse',
    fieldZh: '政治学 · 国际关系', fieldEn: 'Political Science & International Relations',
    styleZh: '他让学生每周写一篇 500 字的政策评论，第二周由另一个学生逐句反驳。他说写得出来是一回事，扛得住反驳才是学术。',
    styleEn: 'A 500-word policy commentary every week, torn apart line by line by another student the week after. Writing it is one thing, he says; surviving the rebuttal is scholarship.',
    workZh: '国际组织决策的文本分析与案例研究。阅读量大，适合文字功底好的学生。',
    workEn: 'Text analysis and case studies of decision-making in international organisations. Reading-heavy; suited to strong writers.',
    ruleZh: '所有引用必须能追溯到一手文献。二手转引一律不算。',
    ruleEn: 'Every citation must trace to a primary source. Second-hand citations do not count.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'guo', group: 'social',
    zh: '郭教授', en: 'Prof. Guo', inst: 'chicago',
    fieldZh: '历史学 · 档案研究', fieldEn: 'History & Archival Research',
    styleZh: '她带学生进档案馆的第一课是：如何在一份 19 世纪的手写账簿里辨认一个数字。她说历史学的技术门槛不比实验室低。',
    styleEn: 'The first lesson in the archive: how to read a single digit in a nineteenth-century handwritten ledger. The technical bar in history, she says, is no lower than in a laboratory.',
    workZh: '近代东亚贸易与移民史的档案整理与数据库建设。有大量数字化与转录工作，可远程。',
    workEn: 'Archival curation and database construction on modern East Asian trade and migration. Substantial digitisation and transcription, remote-eligible.',
    ruleZh: '每一条数据库记录都要标注来源档案的卷宗号。',
    ruleEn: 'Every database record carries the archive’s file reference.',
    spec: { places: 2, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },
];

module.exports.groups = [
  { key: 'life',   zh: '生命与医学', en: 'Life Sciences & Medicine' },
  { key: 'eng',    zh: '工程',       en: 'Engineering' },
  { key: 'comp',   zh: '计算与数据', en: 'Computing & Data' },
  { key: 'phys',   zh: '物理与化学', en: 'Physical Sciences' },
  { key: 'env',    zh: '环境与地球', en: 'Environment & Earth' },
  { key: 'social', zh: '社科与人文', en: 'Social Sciences & Humanities' },
];
