/**
 * 导师阵容（25 位）
 * 前 5 位的姓氏与任职机构由客户提供；其余为示例条目，上线前替换为真实导师。
 * 每位：style（带教习惯）/ work（方法与节奏）/ rule（硬性规矩）三段，避免同质化。
 *
 * 【隐私原则】姓氏 + 大学 + 具体学科 三者叠加足以定位到个人，因此：
 *   · fieldZh/fieldEn 只写宽泛领域组，不写「免疫学」「材料科学」这类具体学科
 *   · work 段只描述方法与节奏（湿实验 / 计算 / 田野 / 档案、可否远程、节奏快慢），
 *     不写研究对象或子领域
 *   · style 与 rule 段写带教习惯，不构成定位，可以具体
 * 新增导师时请沿用这条原则。
 *
 * group 用于筛选：life 生命与医学 · eng 工程 · comp 计算与数据 · phys 物理与化学 · env 环境与地球 · social 社科与人文
 */
module.exports = [
  /* ================= 生命与医学 ================= */
  {
    id: 'huang', group: 'life', real: true,
    zh: '黄教授', en: 'Prof. Huang', inst: 'emory',
    fieldZh: '生命与医学方向', fieldEn: 'Life Sciences & Medicine',
    styleZh: '新学员进组的头两到三个月，任务只有读文献和跟组会。家长常在这个阶段打电话问「是不是什么都没做」，她的回答一向是同一句：一个读不懂文献还假装读懂了的学生，后面做什么都是假的。',
    styleEn: 'For the first two or three months a new student does nothing but read and attend group meetings. Parents often call to ask whether anything is happening; her answer never changes: a student who cannot read a paper and pretends otherwise will be faking everything that comes after.',
    workZh: '课题兼有实验台与数据分析两条路径，学生可以按自己的时间条件选择：假期在地做实验，学期内远程做分析。两条路都要求每周固定出席组会。',
    workEn: 'Projects run along two paths — bench work and data analysis — and students choose by their own calendar: experiments on site over the holidays, analysis remotely during term. Both require fixed weekly attendance at group meetings.',
    ruleZh: '结项时必须能独立复现自己的全部结果。做不到就不出评价信，这一条她从未松口。',
    ruleEn: 'Every student must be able to reproduce all of their own results independently at the end. No reproduction, no evaluation letter. She has never once relaxed this.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '在地 / 远程', modeEn: 'On-site or remote', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'chen', group: 'life',
    zh: '陈教授', en: 'Prof. Chen', inst: 'johns-hopkins',
    fieldZh: '生命与医学方向', fieldEn: 'Life Sciences & Medicine',
    styleZh: '他给每个学生的第一个任务是设计一个对照实验，然后亲自把它做砸——不是恶意，是让学生在第一周就见到「对照组没设好」长什么样。',
    styleEn: 'The first task he gives every student is to design a controlled experiment; then he personally runs it badly — not out of malice, but so the student sees in week one what a poorly set control looks like.',
    workZh: '以实验动物研究为主，学生通常从录像标注与评分起步，做得扎实的才进入成像数据分析。全程在地，节奏由动物实验本身决定，不能挪。',
    workEn: 'Animal-based research. Students start with video annotation and scoring, and only those who do it thoroughly progress to imaging analysis. Entirely on site, with a rhythm set by the experiments themselves and not movable.',
    ruleZh: '实验记录本每周检查一次。记录写得含糊的那周，不算工时。',
    ruleEn: 'Laboratory notebooks are checked weekly. A week with vague entries does not count as hours worked.',
    spec: { places: 2, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'wang', group: 'life',
    zh: '王教授', en: 'Prof. Wang', inst: 'washington',
    fieldZh: '生命与医学方向', fieldEn: 'Life Sciences & Medicine',
    styleZh: '她不接受任何「跑通了」作为进度汇报。学生必须说清跑通的是哪一步、参数为什么这样选、换一批数据会不会崩。',
    styleEn: 'She does not accept “it ran” as a progress report. The student must say which step ran, why those parameters, and whether it would break on a different batch.',
    workZh: '全程计算，可远程，对编程基础有明确要求——进组前要通过一次代码测试。数据量大，学生真正的挑战是把流程写得能重复跑。',
    workEn: 'Entirely computational and remote-eligible, with an explicit programming prerequisite — there is a coding test before joining. The data is large, and the real challenge is writing a pipeline that runs again.',
    ruleZh: '所有代码进课题组的版本库，提交记录里有学生自己的名字。这既是训练，也是证据。',
    ruleEn: 'All code goes into the group’s repository under the student’s own name. It is both training and evidence.',
    spec: { places: 3, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'hu', group: 'life',
    zh: '胡教授', en: 'Prof. Hu', inst: 'cuhk',
    fieldZh: '生命与医学方向', fieldEn: 'Life Sciences & Medicine',
    styleZh: '他习惯让学生先读一篇被撤稿的论文，再读同一课题的正确版本。他说这比讲十堂方法课都管用。',
    styleEn: 'He has students read a retracted paper first, then the correct version on the same topic. He says it does more than ten lectures on method.',
    workZh: '基于真实队列的数据分析，混合模式。因为涉及真实个体记录，流程比一般课题慢，学生要先完成合规培训才能拿到数据。',
    workEn: 'Data analysis on real cohorts, hybrid mode. Because it involves records of real individuals the process is slower than most projects; students complete compliance training before receiving any data.',
    ruleZh: '数据脱敏协议签署前，学生不接触任何一行数据。这条没有例外。',
    ruleEn: 'No student touches a single row of data before signing the de-identification protocol. No exceptions.',
    spec: { places: 2, stageZh: '本科 · 医学预科', stageEn: 'Undergraduate · pre-med', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'wu', group: 'life',
    zh: '吴教授', en: 'Prof. Wu', inst: 'ucl',
    fieldZh: '生命与医学方向', fieldEn: 'Life Sciences & Medicine',
    styleZh: '她要求学生在预注册平台上先公开实验假设，再收数据。她的原话：「先想好你要怎么输，才知道你有没有赢。」',
    styleEn: 'She requires students to pre-register hypotheses publicly before collecting data. Her phrase: “Decide how you would lose before you can know whether you won.”',
    workZh: '线上行为实验，从设计、被试招募到分析由学生独立走完整个闭环。可全程远程，是我们对高中生最友好的课题类型之一。',
    workEn: 'Online behavioural experiments, with the student running the full loop from design through recruitment to analysis. Fully remote, and one of the most accessible project types we offer to secondary students.',
    ruleZh: '任何未预注册的分析，结果里必须标明「探索性」。',
    ruleEn: 'Any analysis not pre-registered must be labelled “exploratory” in the results.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 工程 ================= */
  {
    id: 'yang', group: 'eng', real: true,
    zh: '杨教授', en: 'Prof. Yang', inst: 'florida',
    fieldZh: '工程方向', fieldEn: 'Engineering',
    styleZh: '他不太写长评语，但会把学生做的每一版原型编号存档。到结项时那一串编号本身就是最有说服力的记录：第一版失败在哪里、第七版改了什么。',
    styleEn: 'He does not write long commentary, but he archives and numbers every prototype a student produces. By the end, that numbered sequence is the most persuasive record there is: where version one failed, what changed by version seven.',
    workZh: '以器件原型的反复迭代为核心，判断标准很工程师：东西能不能用，重复几次还一不一样。在地为主，动手时间远多于读文献时间。',
    workEn: 'Built around repeated prototype iteration, judged by an engineer’s standard: does it work, and does it still hold when you repeat it. Primarily on site, with far more hours at the bench than in the literature.',
    ruleZh: '湿实验与器件加工没法远程。适合能安排整段暑期、或就近的学生。',
    ruleEn: 'Bench work and fabrication cannot be done remotely. Suited to students who can commit a full summer, or who are nearby.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '以在地为主', modeEn: 'Primarily on-site', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'lin', group: 'eng',
    zh: '林教授', en: 'Prof. Lin', inst: 'hkust',
    fieldZh: '工程方向', fieldEn: 'Engineering',
    styleZh: '他的组会有一条奇怪的规矩：演示必须用实机，不许放仿真视频。他说仿真里什么都能成功，招生官也知道这一点。',
    styleEn: 'His group meetings have an odd rule: demos must run on real hardware, never a simulation video. Everything succeeds in simulation, he says, and admissions committees know it.',
    workZh: '硬件课题，学生从标定与数据采集起步，能力够的进入算法调参。所有演示必须跑在实机上，不接受仿真录像。',
    workEn: 'Hardware work: students begin with calibration and data capture, and capable ones move into algorithm tuning. Every demonstration must run on real hardware; simulation videos are not accepted.',
    ruleZh: '进实验室前必须通过安全考核。摔坏一台设备的成本，够付半年学费。',
    ruleEn: 'Safety certification before entering the lab. Breaking one piece of equipment costs half a year’s tuition.',
    spec: { places: 2, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'zhang', group: 'eng',
    zh: '张教授', en: 'Prof. Zhang', inst: 'georgia-tech',
    fieldZh: '工程方向', fieldEn: 'Engineering',
    styleZh: '每个学生入组第一周要做一件事：把上一位学生留下的实验装置拆开，画出原理图，再装回去。装不回去的也有——他说那正好是学习的开始。',
    styleEn: 'Every student’s first week: dismantle the apparatus left by the previous student, draw the schematic, reassemble it. Some cannot reassemble it — which, he says, is precisely where learning begins.',
    workZh: '实验装置的搭建与测试，含大量传感器布置与数据采集。适合动手能力强、愿意花时间调装置的学生。',
    workEn: 'Building and testing experimental apparatus, with a great deal of sensor placement and data acquisition. For students who like to build and are willing to spend time on the rig.',
    ruleZh: '所有测量数据必须附不确定度。没有误差棒的图，组会上不许放。',
    ruleEn: 'Every measurement must carry an uncertainty. A figure without error bars is not shown in group meeting.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'he', group: 'eng',
    zh: '何教授', en: 'Prof. He', inst: 'ntu',
    fieldZh: '工程方向', fieldEn: 'Engineering',
    styleZh: '她要求学生用三句话向非专业人士解释自己的课题，说不清楚就回去重读。她说如果你解释不了，你就还没真的懂。',
    styleEn: 'She makes students explain their project in three sentences to a non-specialist; if they cannot, they go back and reread. If you cannot explain it, she says, you do not yet understand it.',
    workZh: '前期做仿真（可远程），后期进洁净室做表征测试。两段的要求很不一样，学生常在过渡处卡住，这正是她认为最值得经历的一段。',
    workEn: 'Simulation in the early stage (remote-eligible), then characterisation in the cleanroom. The two halves demand very different things, and students usually stall at the transition — which is exactly the part she considers most worth going through.',
    ruleZh: '仿真结果必须与至少一组实测数据对得上，否则不进报告。',
    ruleEn: 'Simulation results must agree with at least one set of measured data before they enter a report.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'han', group: 'eng',
    zh: '韩教授', en: 'Prof. Han', inst: 'cmu',
    fieldZh: '工程方向', fieldEn: 'Engineering',
    styleZh: '他的学生每周必须做一次真实用户测试，哪怕只有两个被试。他说设计师最大的错觉是「我觉得用户会这样用」。',
    styleEn: 'His students run a real user test every week, even with only two participants. A designer’s greatest illusion, he says, is “I think users will use it this way.”',
    workZh: '原型设计与真实用户测试交替推进，既有编程也有田野观察。可远程，但每周必须约到真实被试。',
    workEn: 'Prototype design alternating with real user testing — part programming, part field observation. Remote-eligible, but a real participant must be scheduled every week.',
    ruleZh: '用户测试必须有知情同意记录。没有的，数据作废。',
    ruleEn: 'User tests require documented informed consent. Without it, the data is discarded.',
    spec: { places: 3, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 计算与数据 ================= */
  {
    id: 'zhao', group: 'comp', real: true,
    zh: '赵教授', en: 'Prof. Zhao', inst: 'george-mason',
    fieldZh: '计算与数据方向', fieldEn: 'Computing & Data',
    styleZh: '他对学生的第一项训练不是建模，而是把一个含糊的社会问题改写成一个可被数据回答的问题。这一步通常要反复四五轮。很多学生第一次交上来的选题，他的批注只有一句：「这个问题没有答案，因为它没有被问清楚。」',
    styleEn: 'The first thing he trains a student to do is not modelling but rewriting a vague social question into one that data can answer. This usually takes four or five rounds. On a first attempt his annotation is often one line: “This question has no answer, because it has not been asked clearly.”',
    workZh: '以公开的大规模行政数据为素材，从提问到成稿全部可远程。承担了我们绝大部分远程课题，对国内在读学期的学生尤其关键。',
    workEn: 'Built on large-scale public administrative data, fully remote from question to write-up. He carries most of our remote-eligible projects, which matters enormously for students still in school in China.',
    ruleZh: '代码必须附 README 和完整复现步骤，否则不算交付。',
    ruleEn: 'Code must ship with a README and complete reproduction steps, or it is not accepted as delivered.',
    spec: { places: 4, stageZh: '高一起 · 本科', stageEn: 'Grade 10 up · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'li-polyu', group: 'comp', real: true,
    zh: '李教授', en: 'Prof. Li', inst: 'polyu',
    fieldZh: '计算与数据方向', fieldEn: 'Computing & Data',
    styleZh: '每年只接收两名中学生，多一个都不接。理由很直白：三年连续带教，他能记住的学生就这么多；记不住的学生，他写不出有细节的推荐信。',
    styleEn: 'He takes exactly two secondary students a year, never three. His reason is blunt: over three years, two is the number he can genuinely remember, and he cannot write a detailed letter about a student he does not remember.',
    workZh: '长线培养主力导师。第一年文献与工具，第二年独立负责一个子问题，第三年才谈产出。课题为计算方向，可远程，时区与内地相近。',
    workEn: 'The backbone of our institute track: year one literature and tooling, year two an owned sub-question, output not discussed until year three. Computational, remote-eligible, in a time zone close to the mainland.',
    ruleZh: '中途不换导师。换了，三年的记忆就断了。',
    ruleEn: 'No change of mentor mid-track. A change breaks three years of memory.',
    spec: { places: 2, stageZh: '中学长线为主', stageEn: 'Secondary, long track', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '2 – 3 年', minEn: '2 – 3 years' },
  },
  {
    id: 'zhou', group: 'comp',
    zh: '周教授', en: 'Prof. Zhou', inst: 'columbia',
    fieldZh: '计算与数据方向', fieldEn: 'Computing & Data',
    styleZh: '她让学生先用一份已经发表的数据，重做一遍作者的分析。对上了，再开始自己的课题；对不上，先搞清楚为什么——这一步常常就是一篇论文。',
    styleEn: 'She has students re-run a published author’s analysis on the published data first. If it matches, they begin their own project; if not, they find out why — and that alone is often a paper.',
    workZh: '全计算，可远程，数学基础要求高。学生的第一项任务永远是复现别人已经发表的分析，而不是做自己的。',
    workEn: 'Fully computational, remote-eligible, mathematically demanding. A student’s first task is always to reproduce someone else’s published analysis, never their own.',
    ruleZh: '每份分析必须写明「这个结论在什么假设下才成立」。没有这段，稿子退回。',
    ruleEn: 'Every analysis must state the assumptions under which the conclusion holds. Without that paragraph, the draft is returned.',
    spec: { places: 3, stageZh: '本科为主', stageEn: 'Mainly undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'xie', group: 'comp',
    zh: '谢教授', en: 'Prof. Xie', inst: 'cambridge',
    fieldZh: '计算与数据方向', fieldEn: 'Computing & Data',
    styleZh: '他从不直接给答案，只给下一本要读的书。有学生统计过，一个学期他推荐了 23 本，读完 6 本，课题做完了。',
    styleEn: 'He never gives answers, only the next book to read. One student counted: 23 recommendations in a term, 6 actually read, project completed.',
    workZh: '理论与数值并重：用代码验证推导，用推导指导代码，两边都不能偏废。可远程，但要求每周提交手写推导。',
    workEn: 'Theory and computation in equal measure: code verifies the derivation, the derivation guides the code, and neither side may be neglected. Remote-eligible, with handwritten derivations submitted weekly.',
    ruleZh: '推导必须手写。他不看打字的数学。',
    ruleEn: 'Derivations must be handwritten. He does not read typed mathematics.',
    spec: { places: 1, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'tang', group: 'comp',
    zh: '唐教授', en: 'Prof. Tang', inst: 'ubc',
    fieldZh: '计算与数据方向', fieldEn: 'Computing & Data',
    styleZh: '她的学生要先当一个月助教，观察真实课堂，然后才允许碰数据。她说没见过教室的人分析不了教育数据。',
    styleEn: 'Her students spend a month as teaching assistants observing real classrooms before touching data. Someone who has never seen a classroom, she says, cannot analyse education data.',
    workZh: '行为数据分析，可全程远程，对高中生尤其友好。但入组前要先做一个月现场观察——她不接受没见过现场的人分析数据。',
    workEn: 'Behavioural data analysis, fully remote and especially accessible to secondary students. But a month of on-site observation comes first: she does not accept analysis from someone who has never seen the setting.',
    ruleZh: '涉及未成年人数据的分析，每一步都要过伦理审查。慢，但没有捷径。',
    ruleEn: 'Every analysis involving minors’ data passes ethics review at each step. Slow, and without shortcuts.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可全程远程', modeEn: 'Fully remote possible', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 物理与化学 ================= */
  {
    id: 'li-nus', group: 'phys', real: true,
    zh: '李教授', en: 'Prof. Lee', inst: 'nus',
    fieldZh: '物理与化学方向', fieldEn: 'Physical Sciences',
    styleZh: '在我们的导师里，他是最常说「不」的那一位。他明确保留拒绝为不达标工作背书的权利，并且真的用过——有学员的海报被退回三次，第四次才放行；也有学员最终没有拿到他的评价信。',
    styleEn: 'Among our faculty he is the one who says no most often. He retains the right to decline to endorse work that is not good enough, and has used it — one poster was sent back three times before he cleared it; another student finished without his letter.',
    workZh: '以样品制备与表征为主的在地湿实验，对动手能力要求高，适合能安排完整暑期的学生。实验失败率高是常态。',
    workEn: 'On-site bench work centred on sample preparation and characterisation, demanding in practical skill and suited to students who can commit a full summer. A high failure rate is the norm.',
    ruleZh: '这条写进了与他的约定，也写进了与家庭的合同：如果一位导师从不拒绝，那他的认可就不值钱。',
    ruleEn: 'Written into our agreement with him and our contract with families: a mentor who never refuses has an endorsement worth nothing.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '在地湿实验', modeEn: 'On-site, wet lab', minZh: '18 周', minEn: '18 weeks' },
  },
  {
    id: 'ma', group: 'phys',
    zh: '马教授', en: 'Prof. Ma', inst: 'eth',
    fieldZh: '物理与化学方向', fieldEn: 'Physical Sciences',
    styleZh: '他让学生自己搭一台简易的测量装置，哪怕实验室里有现成的。他说用别人的仪器得到的数据，你解释不了噪声从哪来。',
    styleEn: 'He has students build their own rudimentary measurement rig even though the lab has a proper one. With someone else’s instrument, he says, you cannot explain where the noise comes from.',
    workZh: '学生要先自己搭一台简易测量装置，哪怕实验室里有现成的。前期数据处理可远程，测量阶段必须在地。',
    workEn: 'Students build their own rudimentary measurement rig first, even though the laboratory has a proper one. Early data work can be remote; the measurement phase must be on site.',
    ruleZh: '每个数据点必须能追溯到原始文件与测量时间。',
    ruleEn: 'Every data point must trace back to a raw file and a timestamp.',
    spec: { places: 1, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '20 周', minEn: '20 weeks' },
  },
  {
    id: 'xu', group: 'phys',
    zh: '徐教授', en: 'Prof. Xu', inst: 'imperial',
    fieldZh: '物理与化学方向', fieldEn: 'Physical Sciences',
    styleZh: '她要求学生在每次实验前写下预期结果，实验后对照。她说科研的乐趣不在于猜对，在于搞清楚为什么猜错。',
    styleEn: 'She has students write the expected result before every experiment and compare afterwards. The pleasure of research, she says, is not in guessing right but in understanding why you guessed wrong.',
    workZh: '大量重复实验与数据整理，在地进行。适合耐心好、手稳、不怕做四十遍同一件事的学生。',
    workEn: 'A great deal of repetition and data curation, on site. For patient students with steady hands who do not mind doing the same thing forty times.',
    ruleZh: '未经安全培训不得单独操作。培训要考试，不及格重考。',
    ruleEn: 'No unsupervised bench work without safety training, which is examined and retaken on failure.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '在地', modeEn: 'On-site', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'liu', group: 'phys',
    zh: '刘教授', en: 'Prof. Liu', inst: 'ucsd',
    fieldZh: '物理与化学方向', fieldEn: 'Physical Sciences',
    styleZh: '他带学生出过一次海，回来后学生对「数据质量」有了完全不同的理解——晕船的时候记录的数据，可信度是要打折的。',
    styleEn: 'He took students to sea once; they came back with a very different understanding of data quality — readings logged while seasick deserve a discount.',
    workZh: '以观测数据的处理与模型对比为主，可远程；偶尔有随船出海的机会，名额极少且要提前半年安排。',
    workEn: 'Mainly processing observational data and comparing it against models, remote-eligible. Occasional berths at sea come up, but places are very few and must be arranged six months ahead.',
    ruleZh: '所有图的坐标轴必须带单位。他说这条规矩救过他三篇论文。',
    ruleEn: 'Every axis on every figure carries a unit. This rule, he says, has saved three of his papers.',
    spec: { places: 2, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },

  /* ================= 环境与地球 ================= */
  {
    id: 'gao', group: 'env',
    zh: '高教授', en: 'Prof. Gao', inst: 'duke',
    fieldZh: '环境与地球方向', fieldEn: 'Environment & Earth',
    styleZh: '田野采样期间，她要求学生每天写一页手记，记的不是数据，是「今天哪里可能出错了」。这些手记后来成了论文里最诚实的一段。',
    styleEn: 'During field sampling she requires a one-page daily note — not data, but “where might I have gone wrong today”. Those notes later become the most honest paragraph in the paper.',
    workZh: '有田野季也有实验室季，两段都在地。田野期间日晒虫咬是常态，报名前我们会把这件事说清楚。',
    workEn: 'A field season and a laboratory season, both on site. Sun and insects are part of the field period, and we say so plainly before anyone signs up.',
    ruleZh: '田野安全培训是硬门槛。没有例外，包括她自己。',
    ruleEn: 'Field safety training is mandatory — including for her.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '在地为主', modeEn: 'Primarily on-site', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'luo', group: 'env',
    zh: '罗教授', en: 'Prof. Luo', inst: 'purdue',
    fieldZh: '环境与地球方向', fieldEn: 'Environment & Earth',
    styleZh: '他的学生第一天领到的不是文献，是一块试验田。他说农学的所有问题最后都要回到地里去验证。',
    styleEn: 'On day one his students receive not a reading list but a plot of experimental land. Every question in agronomy, he says, ends up being tested in the ground.',
    workZh: '田野与计算各半：一半时间在试验地采集，一半时间处理采集回来的数据。学生第一天领到的不是文献，是一块地。',
    workEn: 'Half field, half computation: half the time collecting on the plot, half processing what was collected. On day one a student receives not a reading list but a piece of land.',
    ruleZh: '田间记录必须当天录入，隔夜的记忆不算数据。',
    ruleEn: 'Field notes are entered the same day. Memory from the night before is not data.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'liang', group: 'env',
    zh: '梁教授', en: 'Prof. Leung', inst: 'hku',
    fieldZh: '环境与地球方向', fieldEn: 'Environment & Earth',
    styleZh: '他让学生先在一个街区走满 20 个小时，画出来，再开始读任何规划理论。他说地图是走出来的，不是画出来的。',
    styleEn: 'Students walk one neighbourhood for twenty hours and draw it before reading any planning theory. A map, he says, is walked, not drawn.',
    workZh: '实地调研与空间分析结合，以在地为主。所有调研必须有人在场记录，不接受纯遥感或纯问卷。',
    workEn: 'Fieldwork combined with spatial analysis, primarily on site. All surveys require an observer physically present; pure remote sensing or pure questionnaires are not accepted.',
    ruleZh: '所有调研必须有人在场记录，不接受纯遥感或纯问卷。',
    ruleEn: 'All surveys require an observer physically present. Pure remote sensing or pure questionnaires are not accepted.',
    spec: { places: 3, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '在地为主', modeEn: 'Primarily on-site', minZh: '12 周', minEn: '12 weeks' },
  },

  /* ================= 社科与人文 ================= */
  {
    id: 'zheng', group: 'social',
    zh: '郑教授', en: 'Prof. Zheng', inst: 'toronto',
    fieldZh: '社科与人文方向', fieldEn: 'Social Sciences & Humanities',
    styleZh: '她的组会不讨论结果，只讨论识别策略：你凭什么说这是因果，而不是相关？回答不了这个问题的分析，不管结果多好看都不进报告。',
    styleEn: 'Her group meetings do not discuss results, only identification: on what grounds is this causal rather than correlational? An analysis that cannot answer stays out of the report, however pretty the result.',
    workZh: '全计算，可远程。组会不讨论结果，只讨论识别策略——你凭什么说这是因果，而不是相关。',
    workEn: 'Fully computational and remote-eligible. Group meetings do not discuss results, only identification: on what grounds is this causal rather than correlational.',
    ruleZh: '所有回归都要报告稳健性检验。一个模型就下结论的，退回重做。',
    ruleEn: 'Every regression reports robustness checks. A conclusion from a single model is sent back.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '14 周', minEn: '14 weeks' },
  },
  {
    id: 'sun', group: 'social',
    zh: '孙教授', en: 'Prof. Sun', inst: 'michigan',
    fieldZh: '社科与人文方向', fieldEn: 'Social Sciences & Humanities',
    styleZh: '他要求学生在做定量分析前先做十次深度访谈。他说数字告诉你「是什么」，访谈告诉你「为什么」，两个都没有的研究是瞎的。',
    styleEn: 'Ten in-depth interviews before any quantitative work. Numbers tell you what, he says; interviews tell you why; research with neither is blind.',
    workZh: '混合方法：定量分析之前要先做十次深度访谈。适合愿意跟人打交道、也坐得住的学生，两样缺一不可。',
    workEn: 'Mixed methods: ten in-depth interviews before any quantitative work. For students willing both to talk to people and to sit still — neither alone is enough.',
    ruleZh: '访谈录音必须逐字转录，由学生自己完成。转录是研究的一部分。',
    ruleEn: 'Interview recordings are transcribed verbatim by the student. Transcription is part of the research.',
    spec: { places: 2, stageZh: '本科', stageEn: 'Undergraduate', modeZh: '混合', modeEn: 'Hybrid', minZh: '16 周', minEn: '16 weeks' },
  },
  {
    id: 'song', group: 'social',
    zh: '宋教授', en: 'Prof. Song', inst: 'lse',
    fieldZh: '社科与人文方向', fieldEn: 'Social Sciences & Humanities',
    styleZh: '他让学生每周写一篇 500 字的政策评论，第二周由另一个学生逐句反驳。他说写得出来是一回事，扛得住反驳才是学术。',
    styleEn: 'A 500-word policy commentary every week, torn apart line by line by another student the week after. Writing it is one thing, he says; surviving the rebuttal is scholarship.',
    workZh: '阅读量极大，每周一篇书面评论，第二周由另一名学生逐句反驳。适合文字功底好、扛得住批评的学生。',
    workEn: 'Reading-heavy, with a written commentary every week torn apart line by line by another student the week after. For strong writers who can take criticism.',
    ruleZh: '所有引用必须能追溯到一手文献。二手转引一律不算。',
    ruleEn: 'Every citation must trace to a primary source. Second-hand citations do not count.',
    spec: { places: 2, stageZh: '高二起 · 本科', stageEn: 'Grade 11 up · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },
  {
    id: 'guo', group: 'social',
    zh: '郭教授', en: 'Prof. Guo', inst: 'chicago',
    fieldZh: '社科与人文方向', fieldEn: 'Social Sciences & Humanities',
    styleZh: '她带学生接触一手材料的第一课是：如何在一份两百年前的手写账簿里辨认一个数字。她说这条路的技术门槛不比实验室低。',
    styleEn: 'The first lesson with primary material: how to read a single digit in a two-hundred-year-old handwritten ledger. The technical bar here, she says, is no lower than in a laboratory.',
    workZh: '一手材料的整理与数据库建设，含大量数字化与转录工作，可远程。技术门槛不比实验室低，只是换了一种技术。',
    workEn: 'Curation of primary material and database construction, with substantial digitisation and transcription, remote-eligible. The technical bar is no lower than a laboratory’s — it is simply a different technique.',
    ruleZh: '每一条数据库记录都要标注来源材料的编号。',
    ruleEn: 'Every database record carries the source material’s reference number.',
    spec: { places: 2, stageZh: '高中 · 本科', stageEn: 'Secondary · undergraduate', modeZh: '可远程', modeEn: 'Remote-eligible', minZh: '12 周', minEn: '12 weeks' },
  },
];

module.exports.groups = [
  { key: 'life',   zh: '生命与医学', en: 'Life Sciences & Medicine' },
  { key: 'eng',    zh: '工程',       en: 'Engineering' },
  { key: 'comp',   zh: '计算与数据', en: 'Computing & Data' },
  { key: 'phys',   zh: '物理与化学', en: 'Physical Sciences' },
  { key: 'env',    zh: '环境与地球', en: 'Environment & Earth' },
  { key: 'social', zh: '社科与人文', en: 'Social Sciences & Humanities' },
];
